name: BrokerCore
role: component
intent: The broker core (broker phase, unit 4) - the transport-agnostic decision engine of the model-decision proxy (Planning/11). It holds the decision as configuration (a compiled recipe + its semantic hash + an injected Proposer + an egress EventSink) and turns one bound request into one enforceable, recorded Decision. It is a thin, security-bearing layer over model.Decide: run the proposer, evaluate the recipe (the kernel does the deciding), emit each ReleaseEvent to the sink (async egress - enforcement never blocks on it), and SHAPE the EvalResult into caller-facing lists the agent host acts on: cleared actions, recommendations (the recommend-only Escalate path), and denials. THE SHAPING LAW (this unit's load-bearing property): a crossing is presented as CLEARED only if it is an Allow at an authoritative sink; nothing Denied or Escalated is ever shaped as cleared; every ReleaseEvent the kernel emits is surfaced in the Decision and written to the sink (none dropped, none fabricated). CEILING: enforcement is synchronous, egress is asynchronous and best-effort (a sink failure is surfaced, never gates); Escalate is refuse-with-recommendation (no live human-approval channel or token mint yet); one recipe per Broker (multi-recipe routing later). The kernel's whole-product invariant is untouched - the broker surfaces it, never relaxes it.
api:
  - "type Action struct { Kind string; Ref string; Sensitivity SinkSensitivity; Subject TrustClass; Verdict Verdict; Released bool }"
  - "type Decision struct { Verdict Verdict; Proposal model.Proposal; Cleared []Action; Recommend []Action; Denied []Action; Events []ReleaseEvent; Fault string; EgressErr string }"
  - "type EventSink interface { Record(ctx context.Context, ev ReleaseEvent) error }"
  - "type MemSink struct { ... }   // in-memory EventSink; MemSink.All() []ReleaseEvent; safe for concurrent Record"
  - "type Broker struct { Recipe stag.Recipe; RecipeHash string; Proposer model.Proposer; Sink EventSink }"
  - func (b Broker) Decide(ctx context.Context, req model.Request) (Decision, error)
behavior:
  - "DECIDE COMPOSES model.Decide: b.Decide runs model.Decide(ctx, b.Recipe, b.RecipeHash, b.Proposer, req). The kernel evaluates the recipe over the proposer's untrusted proposal; the broker adds egress + shaping, never a second gate."
  - "FAIL CLOSED (invariant 8): if model.Decide returns an error (the proposer failed), b.Decide returns a Decision with Verdict Deny, empty Cleared/Recommend/Denied/Events, Fault set to the proposer reason, and the ORIGINAL error - and does NOT touch the sink (nothing crossed, nothing to record). A proposer failure never yields a cleared action."
  - "SHAPING - SINKS: for each SinkOutcome o in the result, build Action{Kind:\"sink\", Ref:o.Field, Sensitivity:o.Sink, Subject:o.Subject, Verdict:o.Verdict, Released:o.Released}. It goes to Cleared IFF o.Sink==SinkAuthoritative AND o.Verdict==Allow (an authoritative effect the host may execute). It goes to Denied IFF o.Verdict==Deny. A benign-sink Allow is inert (logged, not an action) and appears in NEITHER list. No outcome is ever in both Cleared and Denied."
  - "SHAPING - GATES: for each GateOutcome g, build Action{Kind:\"gate\", Ref:g.Id, Verdict:g.Verdict}. It goes to Recommend IFF g.Verdict==Escalate (the recommend-only path: the milestone beyond this checkpoint is handed to a human, not auto-executed) and to Denied IFF g.Verdict==Deny. A passing gate (Allow) appears in neither."
  - "THE SHAPING LAW (surfaces the U7 invariant at the broker boundary): every Action in Cleared has Kind \"sink\", Sensitivity SinkAuthoritative, and Verdict Allow - no Deny, no Escalate, no benign, no gate ever appears in Cleared. For every Cleared action whose Subject is not Authoritative (a genuine crossing), Decision.Events contains a ReleaseEvent with TargetField==Ref AND RecipeHash==b.RecipeHash. Decision.Verdict == the kernel's EvalResult.Verdict exactly."
  - "EGRESS (async, best-effort): Decision.Events == the kernel's emitted events, in order. After shaping, b.Decide calls Sink.Record for each event (when Sink != nil); every emitted event is recorded (Sink.All() equals Decision.Events). A Record error does NOT change the verdict or fail the call - it is surfaced in Decision.EgressErr and b.Decide returns a nil error (enforcement already happened; egress is downstream). This is invariant 9 (enforcement synchronous, egress asynchronous): a sink cannot gate."
  - "DETERMINISTIC: for a deterministic proposer (LocalStub), b.Decide on the same (recipe, hash, req) returns an equal Decision and records equal events; the broker adds no nondeterminism."
constraints: package broker at workspaces/stag/broker (public; import path github.com/scanset/StAG/broker). Depends on the model package, the stag root, and stdlib (context, sync). No third-party dependency.
