name: BrokerCoreTest
role: test
intent: Verify the broker faithfully shapes and records the kernel's decision - and, adversarially, THE SHAPING LAW: nothing denied/escalated is ever presented as cleared, every cleared crossing carries a recorded hash-bound event, and no emitted event is dropped from the Decision or the sink. The fuzz drives random recipes + fuzzed proposals and asserts the Decision is an exact, faithful shaping of stag.Eval, with the sink holding every event. A denied crossing shaped as cleared, or a dropped event, is a product-defining bug.
api:
  - func TestBrokerFixture(t *testing.T)
  - func TestBrokerFailClosed(t *testing.T)
  - func TestBrokerEgress(t *testing.T)
  - func FuzzBrokerShaping(f *testing.F)
prelude: "A stub proposer is model.LocalStub{Default: value}. A randomRecipe(shape []byte, value string) helper builds a stag.Recipe with random ingredients (random TrustClass), a propose step, and several sink/gate/branch steps (random sensitivity, rules, escalate bits) - the FuzzRecipeEval generator - so all outcome kinds (authoritative Allow/Deny, gate Escalate/Deny, benign) are exercised."
behavior:
  - "FIXTURE (the Planning/09 cdn_remediation shape): a Broker over a recipe with an authoritative sink under a set rule + a benign log, RecipeHash a 64-hex value, Proposer LocalStub{Default:\"restart\"}, Sink a *MemSink. b.Decide: Verdict Allow; Cleared has exactly the authoritative sink (Sensitivity SinkAuthoritative, Verdict Allow); Denied and Recommend empty; the benign log is in NEITHER list; Events has one ReleaseEvent (TargetField the sink field, RecipeHash the broker's hash); MemSink.All() equals Decision.Events; Proposal.Value \"restart\". A denied value (\"rm -rf /\") gives Verdict Deny, empty Cleared, the authoritative sink in Denied, zero Events, empty MemSink."
  - "FAIL CLOSED: a Broker whose Proposer is a LocalStub with Err set: b.Decide returns a non-nil error AND a Decision with Verdict Deny, empty Cleared/Recommend/Denied/Events, a non-empty Fault; MemSink.All() is empty (egress untouched). Assert Verdict is Deny even when the error is ignored."
  - "EGRESS BEST-EFFORT: with a sink whose Record always errors, over the happy authoritative-crossing recipe, b.Decide returns a NIL error, the Verdict is still Allow, Decision.Events still holds the event, and Decision.EgressErr is non-empty (a sink cannot gate; enforcement already happened)."
  - "FUZZ FuzzBrokerShaping - THE shaping law. From fuzzed bytes build randomRecipe + a fuzzed proposal value; compute res := stag.Eval(recipe, value, rh) as the independent oracle; run b.Decide with LocalStub{Default:value} and a fresh *MemSink. ASSERT: (1) dec.Verdict == res.Verdict; (2) every a in dec.Cleared has Kind \"sink\", Sensitivity SinkAuthoritative, Verdict Allow (nothing else); (3) dec.Cleared is EXACTLY the set of res.Sinks that are authoritative + Allow (same fields, same count); (4) no field appears in both Cleared and Denied; (5) dec.Recommend is exactly the res.Gates with Verdict Escalate, dec.Denied covers every Deny sink and Deny gate; (6) for every Cleared action with Subject != Authoritative, dec.Events has an event with TargetField==Ref and RecipeHash==rh; (7) dec.Events deep-equals res.Events AND MemSink.All() deep-equals res.Events (nothing dropped, nothing fabricated); (8) every event hashes to 64 hex with nil error. Seed with a releasing value, a denied value, and empty."
constraints: package broker_test (external test); depends on the broker package, the model package, the stag root, github.com/scanset/StAG/internal/gate is NOT needed. reflect, context, fmt, testing.
