name: CanonicalHash
role: component
intent: Deterministic sha256 over canonical JSON (U5) - the Go restatement of ESP's BTreeMap-plus-sort hashing discipline (Planning/03, invariant 11). Given any JSON-marshalable logical value, produce the canonical JSON bytes (object keys sorted at every level, fixed field order) and their sha256. Two properties define it: STABLE (the same logical content hashes identically regardless of Go's randomized map iteration order) and SENSITIVE (any single-field change - a value, an added key, a removed key - changes the hash). This is the hash primitive every signed leaf and every ReleaseEvent (U6, deferred / not yet built) will ride on. HONEST CEILING: this is single-implementation (Go encoding/json) canonical determinism - encoding/json guarantees sorted map keys - NOT full RFC 8785 / JCS cross-implementation canonical form. It is sufficient because StAG is the sole hasher and reconstructs the hash with the same code; it does NOT claim byte-identical canonicalization by a different language's JSON encoder.
api:
  - func CanonicalJSON(v any) ([]byte, error)
  - func CanonicalHash(v any) (string, error)
behavior:
  - "CANONICAL JSON: CanonicalJSON(v) returns json.Marshal(v). encoding/json sorts map keys (documented behaviour) at every nesting level, so a map[string]any encodes with keys in sorted order regardless of Go's randomized map iteration; struct fields encode in declaration (fixed) order. The output is deterministic for any marshalable v."
  - "HASH: CanonicalHash(v) returns the lowercase hex-encoded sha256 of CanonicalJSON(v) - 64 hex characters matching ^[0-9a-f]{64}$. CanonicalHash(v) == hex(sha256(CanonicalJSON(v)))."
  - "STABLE: for two values with identical logical content (the same key/value set built in different orders, or the same map hashed twice while Go iterates it in different random orders), CanonicalHash returns the SAME string."
  - "SENSITIVE: any change to the content - a different value for a key, an added key, a removed key, a changed nested value - yields a DIFFERENT hash."
  - "ERROR / FAIL CLOSED: if v is not JSON-marshalable (a chan, func, complex, or a non-finite float), CanonicalJSON and CanonicalHash return a non-nil error, and CanonicalHash returns an empty string - never a hash of partial or garbage bytes."
  - "NUMERIC TYPING CAVEAT (ceiling): numbers hash by their JSON form, so int(1) and float64(1.0) coincide (both \"1\"), BUT a large integer differs by Go type - int64(9007199254740993) hashes its exact decimal while the float64 of it loses precision (to 9007199254740992). Callers that hash a record and later reconstruct it for verification (Planning/03 intent-reconstruction) MUST use the same Go types; prefer int64 for exact integers and do NOT round-trip a record through json.Unmarshal-into-any (which coerces every number to float64) before hashing."
constraints: package main; standard library only (encoding/json, crypto/sha256, encoding/hex).
