name: ClaudeProposer
role: component
intent: The Claude proposer adapter (broker phase, unit 2) - a model.Proposer implementation that calls the Anthropic Messages API and returns the completion as an UNTRUSTED proposal. It is the second tier of the proposer strategy (LocalStub -> Claude -> OpenRouter/OpenAI); it adds only a transport behind the same interface and inherits every guarantee of the boundary: the returned Proposal is trust-free (Value + provenance only), so a frontier model buys ZERO trust (invariant 3). Lives in its OWN package (model/claude) so the anthropic SDK dependency is quarantined there - a caller using only LocalStub/Decide never pulls the SDK, mirroring the yaml quarantine in the recipe package. CEILING: this is transport glue, not algebra - it does context binding NOT (the Request is assumed already bound), constrains the output to a schema NOT (the gate handles arbitrary strings), and its correctness is verified against a fake HTTP server, never a live model. All assurance is downstream at the gate; the adapter is untrusted and low-assurance by design.
api:
  - "const DefaultModel = anthropic.ModelClaudeOpus4_8   // Haiku 4.5 is the cheap-proposer choice (Planning/08)"
  - "type Claude struct { Model anthropic.Model; MaxTokens int64 }   // plus an unexported client"
  - "func New(model anthropic.Model, opts ...option.RequestOption) Claude"
  - func (c Claude) Propose(ctx context.Context, req model.Request) (model.Proposal, error)
behavior:
  - "IMPLEMENTS model.Proposer: Claude satisfies the model.Proposer interface (compile-time asserted). New builds an anthropic.Client from the options (option.WithAPIKey for prod, option.WithBaseURL for tests); the client is unexported - construction is explicit dependency injection, never a factory/registry keyed on a model-name string (Planning/10 configuration boundary; model selection belongs to the integrator, not StAG)."
  - "REQUEST SHAPE: Propose builds anthropic.MessageNewParams with Model (c.Model, or DefaultModel when empty), MaxTokens (c.MaxTokens, or 1024 when <= 0), a single user message from req.Input (NewUserMessage(NewTextBlock(req.Input))), and System = []TextBlockParam{{Text: req.System}} only when req.System is non-empty. TEMPERATURE, TOP_P, TOP_K ARE NEVER SET - they return HTTP 400 on Opus 4.7+ (verified against docs, Planning/08); output is steered by prompt, not sampling params."
  - "SUCCESS: on a nil-error response whose StopReason is not refusal, Propose concatenates the Text of every TextBlock in resp.Content (in order) into Proposal.Value, and sets Proposal.Model = \"claude:\" + the RESPONSE's served model (resp.Model, honest provenance - what actually produced it), then returns (proposal, nil). The Value is stamped Untrusted downstream by Eval's propose step; the adapter never confers trust."
  - "FAIL CLOSED (invariant 8): any transport/API error from Messages.New is wrapped and returned as (Proposal{}, error) - no partial or fabricated proposal. A StopReason of refusal (the model declined) likewise returns (Proposal{}, error) with a reason, NOT an empty-but-nil success. Both paths make Decide resolve to Deny (the proposer produced nothing to gate); a proposer failure NEVER yields a releasable value."
  - "DETERMINISTIC UNDER A FIXED TRANSPORT: given a transport that returns a fixed response, Propose returns an equal Proposal every call; the adapter adds no nondeterminism of its own (the model's nondeterminism lives on the far side of the HTTP boundary)."
  - "MODEL-INDEPENDENCE PRESERVED (ties to U9): composed via model.Decide, a Claude proposer returning value V yields exactly stag.Eval(recipe, V, recipeHash) - identical to a LocalStub returning V. The verdict depends only on the proposal VALUE, never on the adapter type or the served model; the Claude tier confers no more trust than the stub."
constraints: package claude at workspaces/stag/model/claude (public; import path github.com/scanset/StAG/model/claude). Depends on the model package (Proposer, Request, Proposal), github.com/anthropics/anthropic-sdk-go (+ /option), the stag root only transitively via model, and stdlib (context, fmt, strings). The SDK dependency is quarantined here; the model, recipe, and kernel packages do not import it.
