name: Compose
role: component
intent: Recipe composition — a sub-recipe as an ALTERNATIVE ACTION PATH, by COMPILE-TIME INLINING (Planning/19). A branch case (or the branch default) may target a named sub-recipe with `goto_recipe: <name>` (`default_recipe: <name>`) instead of `goto: <step-id>`. At compile time the named child is resolved, its steps/slots/rules are namespaced with a per-site prefix and SPLICED into the parent (appended after all parent steps, forward-only preserved), and the reference is rewritten to the child's namespaced entry step. The kernel Evals ONE flattened graph — ZERO kernel change; every invariant is re-checked by the EXISTING linter on the composed whole (the inliner is not trusted — its output is re-linted). The parent's semantic hash binds the FULL expansion, so the signed record proves exactly what ran. Cycles and self-reference are rejected at compile time; termination is guaranteed (acyclic, bounded expansion).
api:
  - "recipe.Compose(src []byte, resolve func(name string) ([]byte, error)) (Parsed, []string, error) — front-parse the parent, inline every goto_recipe/default_recipe child via `resolve`, then lint+canonicalize+compile the composed graph; returns the same Parsed (with the FULL-expansion hash) + draft warnings."
  - "recipe.Parse / recipe.ParseDraft are Compose with a reject-all resolver — a recipe that uses goto_recipe via plain Parse errors clearly ('composition requires a recipe store / resolver'); a recipe with NO composition parses exactly as before (regression)."
  - "grammar: a branch case takes EXACTLY ONE of `goto: <id>` | `goto_recipe: <name>`; a branch takes EXACTLY ONE of `default: <id>` | `default_recipe: <name>`. `goto_recipe`/`default_recipe` are legal ONLY on a branch (not propose/sink/foreach)."
concept: author `goto_recipe`/`default_recipe` on a branch; the child is inlined (namespaced, tail) and the composed graph is re-linted + re-hashed; the parent hash binds the whole expansion.
behavior:
  - "INLINES A CHILD: a parent whose branch case has `goto_recipe: <child>` composes into one graph — the child's steps (namespaced `c<site>_<id>`), slots (ingredients + propose out + foreach as), and rule ids are renamed and appended after the parent's steps; the case's target becomes the child's namespaced entry id. Eval of the composed recipe routes through the branch into the (inlined) child and gates as the child would. `default_recipe` behaves the same for the default target."
  - "RE-LINTS THE WHOLE: after splicing, the composed graph goes through the EXISTING lint (declare-before-use, definite-assignment on every path, unique fields, forward-only edges, reachability, gate-protection) and canonical hash. A composition that produces an ill-formed graph fails the linter (the inliner is not trusted). The child's ingredients merge into the composed ingredients (defined-on-all-paths), so a child step reading its own ingredient stays definite across the seam."
  - "HASH BINDS THE EXPANSION: the parent's SemanticHash is computed over the FULLY COMPOSED canonical form (parent + inlined child). Two parents that inline different children hash differently; a parent hashes differently from the same parent with the child edited. The recorded/​signed hash proves the exact composed policy that ran."
  - "FAIL CLOSED — MISSING/CYCLE/SELF/NESTED: an unresolvable child name (resolve returns error) → error; a child whose name equals the parent (self-reference) → error; a child that ITSELF uses goto_recipe/default_recipe (nested composition) → error 'nested composition is not supported in v1'; these never produce a recipe. `resolve` returning bad bytes → the child's own parse error is surfaced."
  - "GRAMMAR + REGRESSION: `goto_recipe`/`default_recipe` are rejected on a non-branch step and when combined with `goto`/`default` on the same case/branch (exactly-one). A recipe with no composition parses/​hashes/​Evals byte-identically to before (Parse == Compose(reject-all)); all existing fixtures unchanged. Same child inlined at two sites → two distinct namespaced copies (no sharing in v1)."
constraints: package recipe at workspaces/stag/recipe (extends the existing parser/linter; refactors parse() to expose a front-parse that Compose splices before lint). Depends on the stag root and the yaml-quarantined parser; no new dependency. v1 constraints (documented, enforced) — composition targets are branch cases/​default only; the child is inlined as a TAIL (runs to its own terminals, no return to parent); NESTING is depth-1 (a child may not itself compose); per-site namespacing means the same child inlined twice is two copies. The resolver is threaded from the recipestore (Store.Get) so the console/live-editor composes; a caller with no store uses the reject-all resolver.
