name: ForeachEval
role: component
intent: foreach - bounded fan-out in the KERNEL (Planning/19). A new closed node kind NodeForeach lets a recipe gate EACH element of a runtime list: the agent/model proposes many candidates (a JSON array), and the deterministic gate disposes each. Eval gains handling for the foreach node - it reads a slot holding a JSON array of strings, binds each element as an UNTRUSTED value into a per-element out-slot, runs the BODY subgraph (the forward nodes after the foreach) once per element, and AndAll-aggregates the verdicts so ONE denied element denies the whole batch. THE LOAD-BEARING PROPERTY, PER ELEMENT: each element that crosses an authoritative sink at Allow still requires a gate verdict AND a recorded ReleaseEvent bound to the recipe hash, carrying the element's untrusted class (the U7v2 invariant, now proven per iteration). Bounded by a FIXED kernel cap (author-unraisable, inv 13); fail-closed Fault on a missing/severed list slot, a value that is not a JSON string array, more than the cap elements, or a nested foreach.
api:
  - "NodeForeach NodeKind — a new closed node kind (ParseNodeKind accepts \"foreach\", String() returns \"foreach\")"
  - "Step.As string — the per-element out-slot bound for each iteration (Step.In is the list slot)"
  - "the existing func Eval(r Recipe, proposal string, recipeHash string) EvalResult gains the foreach case"
  - "const foreachCap — a fixed max element count (e.g. 64), not settable from a recipe"
concept: bounded fan-out; gate each element of a runtime list; per-element untrusted binding + the load-bearing crossing invariant; AndAll aggregation; fixed cap; fail-closed.
behavior:
  - "ITERATES A LIST: at a foreach step, Eval reads slots[Step.In].Value, parses it as a JSON array of strings, and for EACH element e (in order) binds slots[Step.As] = Slot{Value: e, Class: Untrusted, Origin: \"foreach\"} and walks the BODY - the forward subgraph after the foreach node (its Goto / fall-through onward, to the recipe's terminals). The per-element sinks, gates, and events are collected; the overall Verdict is AndAll of the per-element verdicts."
  - "ONE DENIED ELEMENT DENIES THE BATCH: if any element's body walk yields a non-Allow verdict (Deny, Escalate, or a Fault), the aggregated Verdict is non-Allow (AndAll is the existing rollup). An all-Allow batch is Allow."
  - "PER-ELEMENT CROSSING INVARIANT: for each element that reaches an authoritative sink and is released, Eval emits exactly one ReleaseEvent with SubjectClass Untrusted, bound to recipeHash, distinguishable by element (the event Ordering reflects the iteration). An element whose value is outside the release set emits NO event and denies at the sink (fail closed). The count of authoritative release events equals the number of released elements."
  - "EMPTY LIST: an empty array [] yields Verdict Allow with no sinks, gates, or events (nothing to gate, nothing recorded - vacuously safe)."
  - "FAIL CLOSED: a missing/severed Step.In slot, a Value that is not a JSON array of strings, more than foreachCap elements, or a foreach node encountered inside a foreach body (no nesting in v1) each yields Fault (overall Verdict Deny) with no released crossings. Eval never panics on any proposal or recipe."
  - "BOUNDED / MONOTONIC: foreachCap is a fixed kernel constant; no recipe/Step field can raise it (inv 13 - an author knob only moves toward closed). NON-FOREACH RECIPES UNCHANGED: a recipe with no foreach node evaluates exactly as before (the refactor preserves the propose/branch/gate/sink walk)."
constraints: package main/stag at workspaces/stag (the kernel, stag.go). Depends on stdlib (encoding/json for the array parse) and the existing gate/trust/record internals. This unit is the KERNEL change only, tested with hand-built stag.Recipe values; making the PARSER accept `kind: foreach` (it currently recognizes-and-rejects it) is a separate follow-on unit.
