name: OpenAIProposer
role: component
intent: The OpenAI-compatible proposer adapter (broker phase, unit 3) - a model.Proposer that calls a /v1/chat/completions endpoint and returns the completion as an UNTRUSTED proposal. ONE adapter covers every OpenAI-dialect backend by base_url + key: ollama (local, free, :11434/v1), vllm, OpenRouter, and OpenAI. "The OpenRouter piece" is this adapter pointed at OpenRouter - no separate adapter. It is hand-rolled over net/http + encoding/json (the chat-completions payload is trivial), so it adds NO dependency - cleaner than the Claude tier, which needed the anthropic SDK's typed unions. Same boundary guarantees: the returned Proposal is trust-free (Value + provenance), so a better model buys ZERO trust (invariant 3). CEILING: transport glue, not algebra - no context binding (the Request is assumed bound), no schema-constrained output (the gate handles arbitrary strings), correctness verified against a fake HTTP server not a live model. Untrusted and low-assurance by design; all assurance is downstream at the gate.
api:
  - "type Client struct { BaseURL string; APIKey string; Model string; MaxTokens int64; HTTP *http.Client }"
  - func (c Client) Propose(ctx context.Context, req model.Request) (model.Proposal, error)
behavior:
  - "IMPLEMENTS model.Proposer (compile-time asserted). Configuration is explicit fields, not a factory keyed on a provider name (Planning/10): BaseURL selects the backend (ollama/vllm/OpenRouter/OpenAI), APIKey authenticates (ollama ignores it), Model is the served model id, MaxTokens defaults to 1024 when <= 0, HTTP defaults to a client with a sane timeout when nil."
  - "REQUEST SHAPE: Propose POSTs to BaseURL (trailing slash trimmed) + \"/chat/completions\" a JSON body {model: c.Model, max_tokens: N, messages: [{role:\"system\",content:req.System} only when non-empty, {role:\"user\",content:req.Input}]}. Headers: Content-Type application/json, and Authorization: Bearer <APIKey> only when APIKey is non-empty. TEMPERATURE/TOP_P/TOP_K ARE NEVER SENT - the proposer is steered by prompt; the deterministic layer is the gate, not the sampler. The request carries the caller's context."
  - "SUCCESS: on a 2xx response with a non-empty choices array whose first choice's finish_reason is not \"content_filter\", Proposal.Value = choices[0].message.content and Proposal.Model = \"openai:\" + the response's served model (or c.Model if the response omits it) - honest provenance for the OpenAI-compatible dialect. finish_reason \"length\" (truncated at max_tokens) still returns the partial text: the gate refuses a non-member, so a truncated proposal is fail-safe, not fabricated. The Value is stamped Untrusted downstream by Eval; the adapter never confers trust."
  - "FAIL CLOSED (invariant 8): a non-2xx status, a transport error, a context cancellation, a malformed/undecodable body, an empty choices array, or a first-choice finish_reason of \"content_filter\" (the server declined) each returns (Proposal{}, error) - never a partial-but-nil success. All make Decide resolve to Deny; a proposer failure NEVER yields a releasable value."
  - "DETERMINISTIC UNDER A FIXED TRANSPORT: given a transport returning a fixed response, Propose returns an equal Proposal every call; the adapter adds no nondeterminism of its own (the model's lives on the far side of the HTTP boundary)."
  - "MODEL-INDEPENDENCE PRESERVED (ties to U9): composed via model.Decide, an OpenAI-compatible proposer returning value V yields exactly stag.Eval(recipe, V, recipeHash) - identical to a LocalStub or the Claude adapter returning V. The verdict depends only on the proposal VALUE, never on the adapter or the served model."
constraints: package openai at workspaces/stag/model/openai (public; import path github.com/scanset/StAG/model/openai). Depends on the model package and stdlib ONLY (net/http, encoding/json, bytes, context, fmt, io, strings, time). No third-party dependency; the OpenAI dialect is hand-rolled. The stag root enters only transitively via model.
