name: ProposerTest
role: test
intent: Verify the proposer boundary confers zero trust: LocalStub is deterministic and its fail path errors; Decide is a pure composition (Result == Eval of the proposal Value); and - the load-bearing, fuzzed property - MODEL-INDEPENDENCE, that Decide's verdict depends only on the proposal Value and never on which proposer or provenance produced it. Fail-closed on proposer error. A verdict that varies with the model, or a Decide that diverges from Eval, is a product-defining bug.
api:
  - func TestLocalStub(t *testing.T)
  - func TestDecide(t *testing.T)
  - func FuzzDecideModelIndependence(f *testing.F)
behavior:
  - "LOCALSTUB DETERMINISM AND FAIL PATH: a stub with Responses{\"a\":\"x\"} Default \"d\" returns Value \"x\" for Input \"a\", Value \"d\" for a miss, Model \"localstub:<Name>\" in both, and identical Proposals across repeated calls. A stub with Err set returns that error and a zero Proposal, ignoring Responses."
  - "DECIDE IS EVAL: build a recipe (a propose step out=action + an authoritative sink of action under a set rule {restart,isolate,notify}) and a stub returning \"restart\". Decide(ctx, r, rh, stub, req) returns Decision.Result == stag.Eval(r, \"restart\", rh) (equal Verdict Allow, one Event, equal Sinks/Gates/Fault by reflect.DeepEqual), and Decision.Proposal.Value == \"restart\", Decision.Proposal.Model == the stub's model. A denied value (\"rm -rf /\") gives Decision.Result.Verdict Deny with zero events, still == the direct Eval."
  - "FAIL CLOSED: Decide with a stub whose Err is set returns a non-nil error AND Decision.Result.Verdict == Deny with a non-empty Fault naming the proposer error; Eval is not consulted (no event, no sink outcomes). Assert the Verdict is Deny even when the returned error is ignored."
  - "MODEL-INDEPENDENCE (unit-test spot check): two stubs with DIFFERENT Names/Models but the same Responses, over the same recipe and request, yield Decisions whose Results are reflect.DeepEqual and whose Proposal.Model differ. The provenance changed; the verdict did not."
  - "FUZZ FuzzDecideModelIndependence - the load-bearing property. Take a fuzzed proposal value and two fuzzed model-name strings ma, mb. Over a fixed representative recipe (propose + an authoritative sink under a set rule + a benign sink) with a fixed recipeHash, build two LocalStubs that both return the fuzzed value (Default = value) but carry Names ma and mb. Assert: (1) Decide(...,stubA,...).Result is reflect.DeepEqual to Decide(...,stubB,...).Result (model-independence: same value, same verdict regardless of provenance); (2) both Results equal stag.Eval(recipe, value, rh) (Decide is a pure pass-through, adds no trust); (3) Decision.Proposal.Model reflects ma resp. mb (provenance carried, not dropped); (4) every emitted event in the Result hashes to 64 hex with nil error and carries RecipeHash == rh. Seed with a releasing value, a denied value, and empty."
constraints: package model; depends on the stag root package, context, errors, reflect, testing.
