name: Proposer
role: component
intent: The proposer boundary (broker phase, unit 1) - the untrusted agent side, a strategy/adapter seam that produces the proposal string the kernel gates. Its ONE load-bearing property is the inverse of the kernel's: it confers ZERO trust. A Proposal is trust-free BY CONSTRUCTION (no trust class, no sink sensitivity, no rule - trust is conferred only at the gate, U3), so a "better" or "signed" or "authenticated" model cannot express more trust because there is nowhere to put it (invariant 3: trust is conferred by verified origin and the gate's verdict, never by presence or channel). The strategy interface lets a customer bring any agent (LocalStub now; a Claude adapter, then OpenRouter/OpenAI, later - separate units that only add a transport). Decide is the minimal in-process wiring proposer -> Eval: run the proposer, feed its raw Value to stag.Eval (which stamps it Untrusted at the propose step), return the verdict alongside the proposal's provenance. Provenance is RECORDED, never authorizes. CEILING: this unit does NOT do context binding (assembling a scoped, origin-tagged prompt is a separate broker component; Decide treats every Request field as data the proposer reasons over), does NOT constrain the proposal to a schema (the gate handles arbitrary strings; schema-constrained output is a later refinement), and the in-process Decide is NOT the network decision endpoint (MCP/gRPC/HTTP transport is a later unit). The proposer is untrusted and low-assurance by design; the assurance is entirely downstream at the gate.
api:
  - "type Request struct { Recipe string; System string; Input string }"
  - "type Proposal struct { Value string; Model string }"
  - "type Proposer interface { Propose(ctx context.Context, req Request) (Proposal, error) }"
  - "type LocalStub struct { Name string; Responses map[string]string; Default string; Err error }"
  - func (s LocalStub) Propose(ctx context.Context, req Request) (Proposal, error)
  - "type Decision struct { Proposal Proposal; Result EvalResult }"
  - func Decide(ctx context.Context, r Recipe, recipeHash string, p Proposer, req Request) (Decision, error)
behavior:
  - "TRUST-FREE BY CONSTRUCTION: Proposal has exactly two fields, both string - Value (the raw proposal) and Model (provenance). It carries NO trust class, NO sink sensitivity, NO rule. There is no field, method, or path by which a proposer can raise the trust of its output; a better model buys zero trust (invariant 3). This is the load-bearing design property, enforced by the type, verified by review not fuzz."
  - "LOCALSTUB is a deterministic, offline proposer for tests and local wiring (no network). Propose looks up req.Input in Responses; a hit returns Proposal{Value: that, Model: \"localstub:\"+Name}; a miss returns Proposal{Value: Default, Model: \"localstub:\"+Name}. Same Request -> same Proposal, always (determinism). If Err is non-nil, Propose returns (Proposal{}, Err) and consults nothing else (the fail path)."
  - "DECIDE is a PURE COMPOSITION proposer -> gate: it calls p.Propose(ctx, req); on success it computes res := stag.Eval(r, prop.Value, recipeHash) and returns (Decision{Proposal: prop, Result: res}, nil). Decide adds NO trust and performs NO mutation - Decision.Result is EXACTLY Eval(r, Decision.Proposal.Value, recipeHash). The proposal's Value is stamped Untrusted by Eval's propose step, not by Decide."
  - "MODEL-INDEPENDENCE (the fuzzable invariant, 'the model buys zero trust'): Decide's Result is a function of (r, proposal Value, recipeHash) ONLY. For any two proposers that return the same Value for a Request - regardless of their Model provenance string or their concrete type - Decide yields an EQUAL Result (same Verdict, Sinks, Gates, Events, Fault). Model/provenance is carried through into Decision.Proposal.Model but is NEVER an input to the verdict. A verdict that changed with the model would be a product-defining bug."
  - "FAIL CLOSED (invariant 8): if the proposer returns an error, Decide does NOT call Eval (there is no proposal to gate). It returns (Decision{Result: EvalResult{Verdict: Deny, Fault: a non-empty reason naming the proposer error}}, err) - the Deny is carried in the Decision so a caller that ignores the error still sees Deny, and the error is returned so a caller that checks it learns why. A proposer failure NEVER yields Allow or Escalate."
  - "DETERMINISTIC: for a deterministic proposer (LocalStub), Decide on the same (r, recipeHash, req) returns an equal Decision every call; Decide adds no nondeterminism of its own."
constraints: package model at workspaces/stag/model (public; import path github.com/scanset/StAG/model). Depends on the stag root package (Recipe, EvalResult, Eval) and stdlib context/errors/fmt. The dependency direction is outer->inner: the untrusted proposer layer imports the kernel, never the reverse (the kernel must not import model). Stdlib only otherwise; no network in this unit.
