name: ProxyServe
role: component
intent: The HTTP operator surface (Planning/16) over the gating proxy - the backend the Next.js console talks to. It wraps a proxy.Gate (the already-fuzzed decision engine) in a thin, fail-closed HTTP layer. POST /api/decide gates a submitted tool call and returns a legible DecisionView (verdict, forward, the gated value, the rule fired, the sense->reason->decide->act->prove chain, the release events) - a live policy test, no downstream forwarding in this path. GET /api/log returns the signed audit log's verify status + its recorded crossings. GET /api/policies lists the governed tools. GET /api/health is a liveness probe. The gate is invoked ONLY for a well-formed decide request; a malformed body, a missing tool, or a wrong method fails closed to an error status and NEVER invokes the gate or panics; every response is valid JSON. Permissive dev CORS is set so the console (a separate origin in dev) can call it; there is NO auth (internal use only).
api:
  - "type Server struct { Gate proxy.Gate; LogPath string; Pub ed25519.PublicKey; Policies []PolicyView }"
  - "type PolicyView struct { Tool string; Recipe string; GateArg string }"
  - "type ChainView struct { Sense string; Reason string; Decide string; Act string; Prove string }"
  - "type EventView struct { Field string; Rule string; Actor string; Subject string }"
  - "type DecisionView struct { Tool string; Verdict string; Forward bool; Value string; RuleFired string; SubjectClass string; Chain ChainView; Events []EventView; Fault string }"
  - "type VerifyView struct { Count int64; Head string; Signed bool; KeyID string; Verified bool; Error string }"
  - "type LogView struct { Events []EventView; Verify VerifyView }"
  - func (s *Server) Handler() http.Handler
concept: a fail-closed JSON HTTP API over proxy.Gate; decide is a live policy test; log is the signed audit view; the console's backend.
behavior:
  - "DECIDE: POST /api/decide with body {\"tool\":\"write_note\",\"args\":{\"text\":\"hello\"}} decodes the tool call, runs Gate.Decide, and returns 200 with a DecisionView: Verdict = the kernel verdict string, Forward, Value = the gated argument, RuleFired = the authorizing rule of the first release event (or empty), SubjectClass = \"untrusted\" (the agent's proposal is untrusted-until-gated), Chain (sense ok; reason ok if routed else skip; decide = the verdict; act = ok if Forward else skip; prove = ok if any event else skip), Events (each release event as {Field=target field, Rule=authorizing rule, Actor, Subject=subject class}), and Fault. The gate records its crossings to the Gate's Sink as usual."
  - "DECIDE FAILS CLOSED: a request body that is not valid JSON, or has an empty tool, returns 400 with a JSON error and does NOT invoke the gate; a method other than POST returns 405; the gate is invoked ONLY for a well-formed decide request. A well-formed request naming an UNKNOWN tool is a valid request: the gate returns Verdict Deny, Forward false, and the handler returns 200 with that DecisionView (an unknown tool is denied, not an HTTP error)."
  - "LOG: GET /api/log reads LogPath, verifies the hash chain (egress.Verify), and, if a .checkpoint sidecar and Server.Pub are present, verifies the signature (egress.VerifySigned). It returns 200 with a LogView: Verify{Count, Head, Signed (a checkpoint exists), KeyID, Verified (signature checked ok), Error (a non-empty reason if the log or signature does not verify)} and Events (the recorded crossings). A missing log file yields an empty LogView (Count 0), not an error."
  - "POLICIES: GET /api/policies returns 200 with the Policies slice (the governed tools and their recipe + gated argument). HEALTH: GET /api/health returns 200 with {\"ok\":true}."
  - "JSON + CORS ALWAYS: every response has Content-Type application/json and a valid JSON body; Handler sets permissive CORS headers (Access-Control-Allow-Origin *, and answers OPTIONS preflight with 204) so the console can call it cross-origin in dev. No handler panics on any input."
  - "PURE OF SURPRISE: Handler builds a mux over the routes above; unknown paths return 404 with a JSON error. The Server holds only the gate, the log path, an optional public key, and the policy list; it performs no I/O except reading LogPath on /api/log and whatever the Gate's Sink does."
constraints: package serve at workspaces/stag/serve (public; import path github.com/scanset/StAG/serve). Depends on the proxy package (Gate, ToolCall, Decision), the egress package (Verify, VerifySigned, SignedCheckpoint, Leaf), the stag root (ReleaseEvent, Verdict), and stdlib (net/http, encoding/json, crypto/ed25519, bytes, os, io). No MCP dependency (the console tests policies; the MCP proxy is a separate front-end). No auth (internal only).
