name: RealActuators
role: component
intent: Real actuators behind the existing Actuator interface (extending the actuator package): Command execs a program with the gated value, and HTTP posts the gated value to an endpoint. They replace the v1 Stub for effects that actually touch the world. THE LOAD-BEARING SAFETY PROPERTY: a gated value reaches the world only as a DISCRETE argv element (Command, via os/exec — NEVER a shell string) or a JSON body field (HTTP — NEVER URL/header interpolation), so a value can never be shell-interpreted or injected into the request line. This is defense-in-depth ON TOP of complete mediation (U16, fires only cleared): the value is already gated to a closed set, AND its delivery is structurally injection-safe. Both fail closed: a non-zero exit or spawn error (Command) or a non-2xx status / transport error (HTTP) is surfaced as an error, never swallowed.
api:
  - "type Command struct { Name string; Path string; Args []string; Env []string; Timeout time.Duration }"
  - func (c Command) Fire(ctx context.Context, value string) (string, error)
  - "type HTTP struct { Name string; URL string; Method string; Client *http.Client }"
  - func (h HTTP) Fire(ctx context.Context, value string) (string, error)
  - func Argv(args []string, value string) []string
concept: real effects at the actuator boundary; the gated value delivered as a discrete argv element or JSON field; no shell, no request-line injection; fail closed on error.
behavior:
  - "ARGV IS SAFE BY CONSTRUCTION: Argv(args, value) returns a slice equal to args followed by exactly one final element that is value verbatim (len == len(args)+1, last == value, prefix == args). The value is NEVER split, merged, or interpolated into another element. Command builds its exec argv with Argv, so the value is always a single discrete argument."
  - "COMMAND EXECS, NO SHELL: Command.Fire runs Path with Argv(Args, value) via os/exec (exec.CommandContext) — it does NOT invoke a shell, so shell metacharacters in value (;, |, $(), backticks, newlines, quotes) are passed through literally as one argument and never interpreted. On success it returns the combined stdout+stderr and a nil error. If Command.Env is non-empty it is appended to the inherited environment for the child only."
  - "COMMAND FAILS CLOSED: a non-zero exit status, a missing/unexecutable Path, an argument the OS rejects (e.g. a NUL byte in value), or a Timeout expiry each makes Fire return a non-nil error (with any captured output); the error is surfaced, never swallowed. A Timeout > 0 bounds the run via a derived context; 0 means no added deadline."
  - "HTTP POSTS THE VALUE AS DATA: HTTP.Fire sends the value as a JSON body field {\"action\": value} (json-encoded, so any bytes are escaped) with Content-Type application/json to URL using Method (default POST). The value is NEVER placed in the URL, query, or a header. On a 2xx it returns the response body and a nil error."
  - "HTTP FAILS CLOSED: a transport error, or a response status outside 200-299, makes Fire return a non-nil error (with any response body); nothing is treated as success unless the endpoint returned 2xx. A nil Client uses a default with a bounded timeout."
  - "BOTH SATISFY Actuator: Command and HTTP each implement Fire(ctx, value) (string, error), so they drop into a Registry and are fired by FireCleared exactly like Stub — only for a cleared action (U16 unchanged)."
constraints: package actuator at workspaces/stag/actuator (extends the existing package; import path github.com/scanset/StAG/actuator). Depends on stdlib only (context, os, os/exec, time, net/http, encoding/json, bytes, io, fmt) plus the existing broker import already present. No third-party dependency. MCP-tool actuators are a later addition behind the same interface.
