name: RecipeParseTest
role: test
intent: Verify the recipe boundary end to end - the fixture round-trip (YAML -> Parsed -> Eval reproduces the Planning/09 four-path semantics with events bound to the semantic hash), every fail-closed rejection rule with a minimal red YAML each, the two-hash discipline (comments move the artifact hash but never the semantic hash), the draft/strict mode split, and - adversarially - that NO input can panic the parser and that acceptance is deterministic. The rejection table IS the threat research cashed in: every yaml.v3 hazard from Planning/08 has a YAML snippet here that must die with a specific error.
api:
  - func TestRecipeParseFixture(t *testing.T)
  - func TestRecipeParseRejections(t *testing.T)
  - func TestRecipeParseModes(t *testing.T)
  - func TestRecipeParseHashes(t *testing.T)
  - func FuzzRecipeParse(f *testing.F)
behavior:
  - "FIXTURE (the Planning/09 cdn_remediation YAML, verbatim as documented - in:, on_fail: escalate, routes.all broader than the gate, no ingredients section): Parse succeeds with zero-warning equivalence (ParseDraft returns no warnings). Header == {cdn_remediation, 1}. The compiled Recipe: 6 steps in document order with ids propose_plan/choose_path/check_route/apply_route/apply_prefetch/log_only, kinds propose/branch/gate/sink/sink/sink, branch cases resolving routes.all->check_route and cache.approved_classes->apply_prefetch with default log_only, gate rule routes.auto_approvable with Escalate true, sink rules/RuleIDs both bound to their registry entries, actors verbatim, sensitivities authoritative/authoritative/benign. Rules has exactly the three registry entries. Both hashes are 64-hex."
  - "FIXTURE INTEGRATION (the whole product, YAML to verdict): stag.Eval(parsed.Recipe, proposal, parsed.SemanticHash) reproduces the four reference paths - class:regional_fallback -> Allow with ONE event (TargetField aws_route_apply.args.route, AuthorizingRule routes.auto_approvable, RecipeHash == parsed.SemanticHash, Ordering 3); class:release_prewarm -> Allow with one prefetch event, zero gate outcomes; class:transcontinental -> Escalate, zero events, zero sink outcomes, one failed gate outcome; rm -rf / -> Allow with zero events and only the benign log outcome. Fault == \"\" on all four (the lint guarantees the kernel's runtime backstops never fire on a recipe that parsed)."
  - "REJECTIONS - each case is a minimal YAML (usually the fixture with one poison) that must return an error mentioning the offending construct. Prelims: input over 65536 bytes; a UTF-8 BOM; a UTF-16 LE BOM; an embedded NUL; invalid UTF-8. Document: two documents split by ---; an empty document; a top-level sequence. Hygiene: an anchor (&a) anywhere; an alias (*a); a merge key (<<:); a duplicate key in one mapping; an unknown top-level key; depth beyond 32 (nested flow sequences); more than 10000 nodes. Tags and scalars: version: \"1\" (quoted where int required); version: 2; min: 07 / min: +5 / min: 0x1F / min: 1_000 / min: 5.5 / min: 1e3 (each rejects the non-canonical numeral); an unquoted set member (set: [restart]); an unquoted plain no or on in a string position; sensitivity: !!str authoritative with a custom tag variant (!custom) rejects; a !!binary value; a timestamp-shaped unquoted origin (2026-07-01). Names: an uppercase ingredient name; a 65-char id; a rule id with an empty segment (routes..x); a Cyrillic homoglyph key. Ingredients: a value: key under an ingredient; trust: trusted (unknown enum). Rules: kind: set (the OLD spelling, must reject - one register only); set_membership with no set; an EMPTY set; a duplicate set member; signed_equality with signed: \"\"; numeric_range with min > max; numeric_range with a set: key (forbidden cross-field). Steps: a step with no id; duplicate ids; no kind; kind: foreach and kind: exit (each errors.Is ErrNotImplemented and is DISTINCT from kind: frobnicate which is a plain unknown-kind rejection); an out: on a sink (forbidden per-kind key); a goto: on a gate; rule on a benign sink (dead policy); a rule with NO actor on an authoritative sink; in: naming an undeclared slot; in: naming a LATER step's out (declare-before-use); rule: naming an unregistered id; goto: to an unknown id; goto: to an earlier id (backward); a branch with no default; a branch with empty cases; duplicate out: slot names; an out: colliding with an ingredient name; duplicate sink field: strings; an unreachable step (a step after a branch that no edge targets); an authoritative sink fed by an untrusted slot with no rule (guaranteed-Deny); an explicit edge targeting a step INSIDE a gate's guarded segment (a branch case goto straight to the step after a gate). Teaching rejections: when:, loop:, register:, vars:, on: (error text says use in:), and a value containing {{ }}."
  - "MODES: a fixture variant with one extra never-consumed ingredient and one unreferenced rule: ParseDraft succeeds with BOTH warnings (each naming the dead declaration); Parse (strict) rejects. A set containing \"\" (quoted empty member): ParseDraft warns, Parse rejects. Warnings are otherwise empty on the clean fixture."
  - "HASHES: ArtifactHash == hex(sha256(src)) verbatim - asserted against a direct computation. Two sources differing ONLY in comments and blank lines: SAME SemanticHash, DIFFERENT ArtifactHash. Changing one set member, one actor, one on_fail, or the step order: SemanticHash changes. Set member ORDER in the source does not change SemanticHash (canonical form sorts sets) but DOES change ArtifactHash. A rejected input returns zero-value Parsed with empty hashes. Parse of identical bytes twice: reflect.DeepEqual on the two Parsed values."
  - "FUZZ FuzzRecipeParse - the boundary must be unkillable and deterministic. Seeds: the fixture YAML, each rejection-table snippet family (BOM, anchor, merge, deep nesting, non-canonical ints), and byte-level mutations of the fixture. Body takes raw []byte. Assert: (1) Parse NEVER panics (any panic escaping Parse fails the fuzz - the recover contract); (2) if err == nil then a second Parse of the same bytes yields a DeepEqual Parsed (determinism), ArtifactHash == hex(sha256(src)), SemanticHash is 64-hex, Header.Version == 1, the compiled Recipe has >= 1 step, ParseDraft on the same bytes succeeds with zero warnings (strict acceptance implies draft-clean), and stag.Eval(parsed.Recipe, \"class:regional_fallback\", parsed.SemanticHash) terminates with Fault == \"\" (a parsed recipe NEVER trips the kernel's structural backstops - the lint laws subsume them); (3) if err != nil then Parsed is the zero value (reject-before-hash: no hash escapes a rejected file)."
constraints: package recipe (external test file may be package recipe to reach internals if needed, but prefer the public surface); depends on the stag root package, crypto/sha256, reflect, errors, strings, testing.
