name: RecipeEvalTest
role: test
intent: Verify the kernel composes over the ratified recipe graph (U1-U6 wired by the path-walking Eval) and, adversarially, THE whole-product invariant over RUNTIME-CHOSEN EDGES: no non-authoritative value reaches an authoritative sink at Allow without a recorded ReleaseEvent bound to the recipe hash. The table test drives the Planning/09 cdn_remediation fixture down all three reference paths (auto-Allow, gate-Escalate, spoof-inert) plus every fail-closed backstop; the fuzz builds RANDOM GRAPHS - random kinds including junk, random forward/backward/dangling edges, random branch cases and gate escalate bits - and asserts the invariant, the rollup law, and escalate provenance on every path the graph chooses. A single path that Allows a crossing without an event, emits a spurious event, escalates from anywhere but a declared gate, or fails open on a bad edge is a product-defining bug.
api:
  - func TestRecipeEval(t *testing.T)
  - func FuzzRecipeEval(f *testing.F)
behavior:
  - "THE FIXTURE (Planning/09 cdn_remediation in struct form): ingredients none needed beyond the proposal; rules routes.all = set{class:regional_fallback, class:edge_only, class:transcontinental} (branch routing, deliberately BROADER than the gate), routes.auto_approvable = set{class:regional_fallback, class:edge_only} (gate + sink), cache.approved = set{class:release_prewarm} (prefetch sink). Steps: propose_plan (propose, out plan) -> choose_path (branch on plan: case routes.all -> check_route, case cache.approved -> apply_prefetch, default log_only) -> check_route (gate on plan, rule routes.auto_approvable, Escalate=true) -> apply_route (auth sink, in plan, rule routes.auto_approvable + rule id + actor, goto log_only) -> apply_prefetch (auth sink, in plan, rule cache.approved + rule id + actor) -> log_only (benign sink, in plan)."
  - "PATH 1 AUTO-ALLOW: Eval(fixture, \"class:regional_fallback\", rh) with a 64-hex rh: Verdict==Allow, Fault==\"\", exactly ONE event (TargetField==apply_route's field, AuthorizingRule==its rule id, RecipeHash==rh, Ordering==int64(3) the sink's DOCUMENT index), Gates has exactly one outcome {Passed:true, Verdict:Allow}, Sinks has the auth sink (Allow, Released) AND the benign log (Allow) - reached via goto - and NOT apply_prefetch (the non-taken path produced nothing)."
  - "PATH 2 PREFETCH-ALLOW: Eval(fixture, \"class:release_prewarm\", rh): branch routes past the gate to apply_prefetch; Verdict==Allow, ONE event (prefetch field, Ordering==int64(4)), ZERO GateOutcomes (the gate was never reached), and the benign log reached by fall-through."
  - "PATH 3 ESCALATE (the recommend-only path): Eval(fixture, \"class:transcontinental\", rh): branch matches routes.all, the gate's narrower rule fails on a present value with Escalate declared -> Verdict==Escalate, the walk HALTED at the gate: ZERO events, ZERO SinkOutcomes (the actuator was never reached), Gates has exactly one {Passed:false, Verdict:Escalate}, Fault==\"\"."
  - "PATH 4 SPOOF-INERT: Eval(fixture, \"rm -rf /\", rh): no case matches, default routes to log_only; Verdict==Allow with ZERO events and ZERO GateOutcomes and only the benign sink outcome - the attempt is recorded (benign) and no authoritative sink was ever reached; a proposal that somehow reached one unreleased would still Deny (asserted separately below)."
  - "GATE DEFAULTS TO DENY: the fixture with check_route.Escalate=false and the escalating proposal: Verdict==Deny, one GateOutcome {Passed:false, Verdict:Deny}, walk halted."
  - "ESCALATE NEVER SOFTENS UNCERTAINTY: a gate with Escalate=true whose In names a MISSING slot yields GateOutcome{Passed:false, Verdict:Deny} (not Escalate) and halts; a gate with Escalate=true and a NIL Rule likewise yields Deny and halts."
  - "FAULTS FAIL CLOSED (each: Fault != \"\", Verdict==Deny, walk halted): a Goto naming an unknown id; a Goto naming an EARLIER step (backward edge); a branch whose In names a missing slot; a branch where no case matches and Default==\"\"; a Step.Kind outside the four kinds (the v1 silent-skip gap, now a Deny halt)."
  - "SINK DENY DOES NOT HALT: a linear recipe with an unreleased untrusted->authoritative sink FOLLOWED by a benign sink: both SinkOutcomes present (Deny then Allow), Verdict==Deny (rollup), ZERO events - the crossing was refused but the movement continued."
  - "V1 BACK-COMPAT (linear recipes, no ids/gotos/branch/gate): the original table holds under the 3-arg Eval - happy released crossing (Allow, one event, Untrusted subject); denied non-member (Deny, zero events); authoritative subject (Allow, zero events - not a crossing); benign sink (Allow, zero events); missing slot at a sink (Deny, zero events, severed); two-sink rollup one released one not (Deny); empty recipe (Allow); determinism (repeated calls equal)."
  - "RECIPE HASH THREADING: every emitted event's RecipeHash equals the recipeHash argument verbatim; Eval with rh==\"\" emits events with RecipeHash==\"\" (permitted, visible); two Evals differing only in rh yield events whose Hash() differ."
  - "NODEKIND REGISTER: the four String() spellings are propose/sink/branch/gate; NodeKind(99).String()==\"unknown\"; ParseNodeKind round-trips each of the four with nil error; ParseNodeKind of \"foreach\", \"exit\", \"unknown\", \"\", \"Propose\", \" gate \" each returns (NodeKind(-1), non-nil error)."
  - "EVENTS ARE VALID RECORDS: every event in every table case returns a nil error and a 64-hex Hash() (ties U7 -> U6 -> U5)."
  - "FUZZ FuzzRecipeEval - THE invariant over runtime-chosen edges. From fuzzed bytes build a RANDOM GRAPH: a few ingredients with random TrustClass (byte%4, out-of-set exercised) and origins; a small rule pool (a set rule over fixed members, a numeric range, nil); 1..8 steps with ids s0..sN, each kind from byte%5 (the four kinds plus a JUNK kind to exercise the Fault path), random In/Out drawn from {ingredient names, propose outputs, a missing name}, random Sensitivity (byte%3, unregistered exercised), random Rule from the pool, random Goto from {\"\", a valid forward id, a dangling id, a backward id}, branches with 0..2 Cases (rules from the pool, random targets) and random Default (sometimes empty), gates with a random Escalate bit. Eval with a fuzzed proposal and recipeHash. ASSERT: (1) THE INVARIANT - every SinkOutcome with Verdict==Allow, Sink==SinkAuthoritative, Subject != Authoritative has a matching event (TargetField) and every such event carries RecipeHash==the argument; (2) THE CONVERSE - every event maps to some executed cleared crossing (authoritative sink outcome, non-authoritative subject, Released, Allow); (3) ROLLUP LAW - result.Verdict == AndAll(every GateOutcome.Verdict, every SinkOutcome.Verdict, plus one Deny iff Fault != \"\"); (4) ESCALATE PROVENANCE - result.Verdict==Escalate implies some GateOutcome.Verdict==Escalate, and every Escalate GateOutcome came from a step with Escalate=true (never from a severed slot or nil rule - those Deny); (5) every event Hash()es to 64 hex with nil error and Ordering is a valid document index of an authoritative sink step; (6) DETERMINISM - a second identical Eval returns an equal result. Seed the corpus with the four fixture paths. The walk terminating at all on adversarial edges IS part of what is proven (forward-only or halt)."
constraints: package stag (module root); standard library plus internal/gate for AndAll in the rollup assertion.
