name: RecipeEval
role: component
intent: The in-memory composition of the whole kernel (U7, evolved to the ratified recipe graph of Planning/09) - the integration proof that U1-U6 compose into the product's load-bearing guarantee over a PATH-FOLLOWING graph walk. Eval walks ONE path through a Recipe (declared, labeled ingredients plus an ordered list of Steps whose kinds are the closed set {propose, sink, branch, gate}), takes an OPAQUE proposal (the agent's untrusted output - no model call, no network) and the semantic hash of the authored recipe document, and produces the verdict, the per-sink and per-gate outcomes, and the ReleaseEvents. Non-taken paths do not execute: a step never reached produces no outcome, no verdict, no event. BRANCH ROUTES, GATES ENFORCE (Planning/09 law, Planning/10 layers): a branch selects the path over the same closed predicate vocabulary as release rules and can never allow anything; a gate is an enforcement checkpoint that halts the walk on failure; every authoritative sink still runs GateSink with its release rule and emits the ReleaseEvent on an allowed crossing REGARDLESS of graph shape - gate nodes add checkpoints, they never replace the crossing gate. Gates are the structural source of Escalate (the recommend-only path): a failing gate yields Deny by default or Escalate only when explicitly declared (the monotonic-knob rule - no authored choice moves a verdict toward Allow). THE LOAD-BEARING INVARIANT, unchanged and re-proven over runtime-chosen edges: no non-authoritative value ever reaches an authoritative sink at Allow without BOTH a gate verdict AND a recorded ReleaseEvent (invariant 2, structural not observed - the same step that allows the crossing records it, now carrying the recipe_hash that binds the crossing to its authorizing document). CEILING: foreach and exit are still deferred (recognized by the parser, rejected before hash); Eval takes a single proposal value (every propose step binds the same value); multi-recipe composition is deferred; the author-time linter proves edge/reachability laws before signing, and Eval enforces fail-closed runtime backstops (Fault) for everything the linter would have rejected.
api:
  - "type Slot struct { Value string; Class TrustClass; Origin string }"
  - type NodeKind int
  - "const ( NodePropose NodeKind = iota; NodeSink; NodeBranch; NodeGate )"
  - func (k NodeKind) String() string
  - func ParseNodeKind(s string) (NodeKind, error)
  - "type Case struct { Rule *ReleaseRule; Goto string }"
  - "type Step struct { Id string; Kind NodeKind; Out string; In string; Sensitivity SinkSensitivity; Rule *ReleaseRule; RuleID string; Field string; Actor string; Goto string; Escalate bool; Cases []Case; Default string }"
  - "type Recipe struct { Ingredients map[string]Slot; Steps []Step }"
  - "type SinkOutcome struct { Field string; Subject TrustClass; Sink SinkSensitivity; Released bool; Verdict Verdict }"
  - "type GateOutcome struct { Id string; Subject TrustClass; Passed bool; Verdict Verdict }"
  - "type EvalResult struct { Verdict Verdict; Sinks []SinkOutcome; Gates []GateOutcome; Events []ReleaseEvent; Fault string }"
  - func Eval(r Recipe, proposal string, recipeHash string) EvalResult
  - "func CanonicalHash(v any) (string, error)   // re-export of U5 for the parser/broker: ONE hashing discipline"
  - "func ParseTrustClass(s string) (TrustClass, error)         // re-export of the U1 inverse"
  - "func ParseSinkSensitivity(s string) (SinkSensitivity, error) // re-export of the U3 inverse"
  - "func ParseRuleKind(s string) (RuleKind, error)             // re-export of the U4 inverse"
behavior:
  - "FACADE RE-EXPORTS: CanonicalHash and the three Parse inverses are thin verbatim wrappers over internal/record and the internal Parse functions - no added logic, so the internal unit specs (U1/U3/U4/U5) remain the single source of their semantics. They exist so the recipe parser and brokers use the SAME hashing discipline and the SAME fail-closed enum registers as the kernel, never a private copy."
  - "NODEKIND REGISTER: NodePropose.String()==\"propose\", NodeSink==\"sink\", NodeBranch==\"branch\", NodeGate==\"gate\", any other NodeKind ->\"unknown\". ParseNodeKind is the exact fail-closed inverse: the four canonical spellings parse to their kinds with nil error; ANY other input (including \"foreach\", \"exit\", \"unknown\", \"\", padded or cased variants) returns (NodeKind(-1), non-nil error). foreach/exit recognition-with-distinct-rejection is the PARSER's vocabulary table (broker phase), not the kernel's."
  - "THE WALK: Eval binds a slot table from r.Ingredients, then walks Steps starting at index 0. Each executed step computes the next index: for propose, sink, and a PASSING gate, Goto==\"\" means fall-through to index+1, else the step whose Id matches Goto; for branch, the matched Case's Goto or Default. Ids resolve by FIRST occurrence in document order (duplicate ids are a linter rejection; Eval stays deterministic). EDGES ARE FORWARD-ONLY: a resolved target must exist and its index must be STRICTLY GREATER than the current index. The walk ends when the next index passes the last step, or when it HALTS (gate failure or Fault). Termination is structural: every transition strictly increases the index or halts."
  - "FAULT (the fail-closed runtime backstop, invariant 8/10): the walk halts immediately with EvalResult.Fault set to a non-empty reason and ONE Deny contributed to the rollup when it meets anything the author-time linter would have rejected: a Goto/Case.Goto/Default naming an unknown id or a non-forward target; an EMPTY edge on a taken branch route (branch edges are always explicit: a matched Case with Goto==\"\", or no match with Default==\"\", is a Fault - the \"\"-means-fall-through convention applies only to non-branch steps); a branch whose input slot is missing (routing on uncertainty is refused); or a Step.Kind outside the four defined kinds (complete mediation - v1 silently SKIPPED unknown kinds; that gap is closed: unknown kind is now a Deny halt). Fault==\"\" on every run that completes or halts at a gate."
  - "PROPOSE: binds the OPAQUE proposal into slot Step.Out as Slot{Value: proposal, Class: Untrusted, Origin: \"propose\"} - untrusted-until-gated regardless of anything else. Every propose step binds the same single proposal value (the v1 ceiling, stated)."
  - "SINK (the crossing gate - refuses the CROSSING, never the movement): look up slot Step.In; a MISSING slot fails closed as a severed label (out-of-set TrustClass) and NEVER releases - released is computed ONLY for a present slot (released := present && Step.Rule != nil && Step.Rule.Release(s.Value), U4), so even a rule whose Set enumerates \"\" cannot clear a crossing for an absent input and an authoritative sink denies a missing slot UNCONDITIONALLY (mirrors the gate's presence requirement; adversarial finding, U7 v2). v := GateSink(s.Class, Step.Sensitivity, released) (U3). Append SinkOutcome{Field, Subject: s.Class, Sink, Released, Verdict: v}. A Deny at a sink does NOT halt the walk: the sink refuses the value's crossing, the walk continues, and the rollup carries the Deny. Only gates and Faults halt."
  - "CROSSING RECORD: append a ReleaseEvent IFF Step.Sensitivity==SinkAuthoritative AND s.Class != Authoritative AND released - SubjectClass=s.Class, SubjectOrigin=s.Origin, CollectedField=Step.In, TargetClass=Authoritative, TargetField=Step.Field, AuthorizingRule=Step.RuleID, Actor=Step.Actor, Ordering=int64(the step's DOCUMENT index, stable whether or not earlier steps were skipped by branching), RecipeHash=the recipeHash argument VERBATIM (U6: the event binds the crossing to its authorizing document; \"\" is permitted and visible)."
  - "GATE (the checkpoint - guards the MOVEMENT): look up slot Step.In and evaluate Step.Rule against its value. A gate always yields exactly one GateOutcome{Id, Subject, Passed, Verdict} when executed. PASS (Rule != nil AND slot present AND Rule.Release(value)): Verdict=Allow (the AndAll identity), walk continues via Goto/fall-through. FAIL on a present value with a real rule: Verdict = Escalate if Step.Escalate else Deny, and the walk HALTS on that path. SEVERED (missing slot) or ABSENT RULE (nil): Verdict=Deny and halt REGARDLESS of Step.Escalate - the declared escalate softens only a genuine predicate failure on a present value; uncertainty always resolves to Deny (invariant 8). The zero value of Step.Escalate is false (Deny): the monotonic-knob rule - the author's on-fail choice selects between two non-Allow outcomes and defaults to the most closed."
  - "BRANCH (routing, never enforcement): look up slot Step.In; a missing slot is a Fault (see above). Cases are tested in document order; the FIRST case whose Rule is non-nil and Release(value) is true routes to its Goto; a nil-Rule case never matches (fail closed - nothing routes on no predicate). No case matches: route to Default. Branch edges are always explicit non-empty forward ids (see FAULT). A branch contributes NO verdict and NO outcome record - it selects among paths whose sinks and gates do all enforcing; a branch may route on untrusted data safely because every path still ends at gated sinks."
  - "ROLLUP: EvalResult.Verdict = AndAll (U2) over, in execution order: every GateOutcome.Verdict, every SinkOutcome.Verdict, plus one Deny iff Fault != \"\". An empty walk (no gates, no sinks, no fault) yields Allow (the AndAll identity). ESCALATE PROVENANCE: gates are the only source of Escalate - result.Verdict==Escalate implies some GateOutcome.Verdict==Escalate."
  - "THE LOAD-BEARING INVARIANT (re-proven over runtime-chosen edges): for every SinkOutcome o, if o.Verdict==Allow AND o.Sink==SinkAuthoritative AND o.Subject != Authoritative, then Events contains a ReleaseEvent with TargetField==o.Field and RecipeHash==the recipeHash argument. CONVERSE: every emitted event corresponds to a real cleared crossing (an executed authoritative sink, non-authoritative subject, released, Allow). Both halves are structural: the same evaluation step produces the verdict and the record, on every path the graph can choose."
  - "DETERMINISTIC: Eval is a pure function of (Recipe, proposal, recipeHash) - slots by key, steps by index, ids by first occurrence; the same inputs yield the same EvalResult and the same events, each hashing stably via U6/U5. BACK-COMPAT: a linear v1-shaped recipe (no Ids, no Gotos, no branch/gate steps) evaluates exactly as v1 did - same outcomes, verdict, and events, now with RecipeHash threaded."
constraints: package stag (module root). Composes internal/trust (U1), internal/gate (U2+U3), internal/release (U4), internal/record (U5+U6); re-exports the primitive types/constants callers need. Standard library only.
