name: ReleaseEvent
role: component
intent: The first-class, hashed record of ONE trust-crossing (U6) - the object ESP never had to represent, because ESP compares-and-discards while StAG must ATTEST a value crossing from untrusted toward an authoritative field (Planning/03). A ReleaseEvent records the four Sabelfeld-Sands dimensions of a declassification: WHAT crossed (subject_class + collected_field), WHERE to (target_class + target_field), by WHOSE authority and under WHICH rule (actor + authorizing_rule), and WHEN in sequence (ordering) - plus recipe_hash, which pins WHICH DOCUMENT the authorizing rule id resolves in (the semantic hash of the authored recipe, Planning/08 decision 2): an id is only meaningful against a document, so the hash makes a signed event traceable to a signed recipe without broker context. Its Hash() is the deterministic sha256 of its canonical form via U5, so the record is TAMPER-EVIDENT: any single-field change changes the hash. U6 is a PASSIVE record - it does NOT enforce that the crossing is valid (U3 gates it, U4 authorizes it, U7 composes); it faithfully captures and fingerprints what happened. It records the crossing's metadata, NOT the raw value that crossed (a deliberate Planning/03 choice). CEILING: it inherits U5's hash ceiling (Go-deterministic, not RFC 8785; ordering is int64 for exact hashing per the numeric-typing caveat) and it is descriptive - it attests a crossing, it does not make the crossing safe.
api:
  - "type ReleaseEvent struct { SubjectClass TrustClass; SubjectOrigin string; CollectedField string; TargetClass TrustClass; TargetField string; AuthorizingRule string; Actor string; Ordering int64; RecipeHash string }"
  - func (e ReleaseEvent) Hash() (string, error)
behavior:
  - "CANONICAL FORM: Hash() canonicalizes the event to a map keyed by the nine snake_case dimension names - subject_class, subject_origin, collected_field, target_class, target_field, authorizing_rule, actor, ordering, recipe_hash - with the two TrustClass fields rendered by their String() (legible names like \"untrusted\" / \"authoritative\", or \"unknown\" for an out-of-set class) and ordering as the int64, then returns CanonicalHash of that map (U5)."
  - "TAMPER-EVIDENT / SENSITIVE: changing ANY one of the nine fields changes Hash(). Two events differing in even a single field - including an out-of-set class that renders \"unknown\", a one-off ordering, or a one-character recipe_hash edit - hash differently."
  - "STABLE / DETERMINISTIC: the same event value hashes to the same string every time (the canonical map is key-sorted by U5, independent of Go map iteration); Hash() is a pure function of the nine fields."
  - "RECIPE HASH IS PASSIVE DATA: RecipeHash carries the semantic hash of the authored recipe document (a 64-hex CanonicalHash produced by the parser); U6 records it VERBATIM like every other string field and does NOT validate its format. The zero value \"\" is structurally permitted at this layer (U7 populates the field when it emits the event; the parser/broker owns supplying a real hash) and hashes distinctly from any non-empty value, so an event missing its recipe binding is itself tamper-evident."
  - "LEGIBLE: the hashed canonical form uses the String() names of the trust classes, not their integer values, so the record is a human-diffable claim (invariant 7: legibility, not soundness)."
  - "PASSIVE / FAIL CLOSED: Hash() returns U5's (string, error). For a well-formed event (all fields are string, int64, or TrustClass) the canonical form is always marshalable, so the error is nil; it propagates a non-nil error and an empty string only if the canonical form were somehow unmarshalable. U6 does NOT check that SubjectClass is less trusted than TargetClass or that the crossing was authorized - that is U3/U4/U7 - and does NOT verify RecipeHash points at a real recipe (the verifier resolves it)."
constraints: package main; standard library only. Depends on TrustClass (U1) and CanonicalHash (U5), both in the same flat package.
