name: ReleaseRule
role: component
intent: The declassifier's release predicate (U4) - the hard center's evaluation step (Planning/02). A ReleaseRule is a CLOSED, enumerable predicate declared in advance; given one candidate value it returns whether THAT value may be released (cleared to cross from untrusted toward an authoritative field), or refuses. Three kinds ONLY (invariant 6): membership in a declared enumerable set, equality against a declared signed value, a bounded numeric range. It is deliberately narrower than a policy language: NO free computation, NO content inspection, NO substring/prefix/regex/normalization/"looks clean" - a predicate that judges open-ended content is a content grader in disguise and fails to laundering. Release is EXACT matching and bounds only. U4 decides one value's release; it does NOT emit the ReleaseEvent (U6) and does NOT decide the sink verdict (U3 consumes this boolean). HONEST CEILING: closed-set release is LEGIBLE and auditable, never provably safe; this component makes the safe cases exact and the unsafe cases unexpressible - it does not solve declassification.
api:
  - type RuleKind int
  - const ( RuleSetMembership RuleKind = iota; RuleSignedEquality; RuleNumericRange )
  - func (k RuleKind) String() string
  - func ParseRuleKind(s string) (RuleKind, error)
  - type ReleaseRule struct { Kind RuleKind; Set []string; Signed string; Min int64; Max int64 }
  - func (r ReleaseRule) Release(value string) bool
behavior:
  - "KIND STRING: RuleSetMembership -> \"set_membership\", RuleSignedEquality -> \"signed_equality\", RuleNumericRange -> \"numeric_range\"; any RuleKind outside the three -> \"unknown\". These snake_case spellings are the SINGLE canonical register shared by recipe YAML and signed records (Planning/08 decision 1); there is no second spelling."
  - "PARSE RULE KIND: ParseRuleKind is the EXACT inverse of String over the three kinds - ParseRuleKind(\"set_membership\")==RuleSetMembership, ParseRuleKind(\"signed_equality\")==RuleSignedEquality, ParseRuleKind(\"numeric_range\")==RuleNumericRange, and ParseRuleKind(k.String())==k for each valid k. Any other input (the old \"set\"/\"signed-equality\"/\"numeric-range\" spellings, \"unknown\", empty, whitespace-padded, or any junk) returns (RuleKind(-1), non-nil error) - fail closed (invariant 8). The sentinel RuleKind(-1) releases nothing (Release==false for every value) and Strings as \"unknown\"."
  - "SET MEMBERSHIP: Release(value) is true IFF value is EXACTLY equal (byte-for-byte, ==) to some element of Set. No trimming, no case-folding, no Unicode normalization, no substring or prefix match. An empty (nil) Set releases nothing."
  - "SIGNED EQUALITY: Release(value) is true IFF Signed is NON-EMPTY and value == Signed exactly. An empty (unconfigured, zero-value) Signed releases nothing (fail closed, invariant 8). The 'signed'/authority dimension (WHO may release) is enforced elsewhere; here it is exact equality against the declared reference value."
  - "NUMERIC RANGE: parse value as a base-10 int64 via strconv.ParseInt(value, 10, 64). Release is true IFF the parse SUCCEEDS, the value is in CANONICAL form (value == strconv.FormatInt(n, 10), so NO leading '+', NO leading zeros, NO '-0'), and Min <= n <= Max (inclusive). Canonical form keeps the accepted STRINGS a finite enumerable set (invariant 6), not an unbounded family of formatting variants ('7', '07', '007', '+7' ...) that all parse to the same number. A non-numeric value, non-canonical spelling, overflow, or any leading/trailing junk or whitespace yields false. If Min > Max (an empty range) nothing is released."
  - "FAIL CLOSED (invariant 8): a RuleKind outside the three defined kinds releases NOTHING - Release returns false for every value. Every refusal path returns false; there is no default-true anywhere."
  - "THE LOAD-BEARING PROPERTY - LAUNDERING RESISTANCE (invariant 6, Planning/02): Release(value)==true IMPLIES value is a true member of the closed rule (an exact Set element, the exact non-empty Signed value, or the CANONICAL decimal spelling of a number within [Min,Max]). The accepted set is finite and enumerable for every kind. No crafted value outside the declared closed set is EVER released. This is the property U4's fuzz target exists to prove; a single non-member that releases is a laundering hole and a product-defining bug, not a test failure."
constraints: package main; standard library only (strconv for the range parse).
