name: ReleaseRuleTest
role: test
intent: Verify the three release-predicate kinds by table, the fail-closed refusals, and - adversarially - the laundering-resistance property that release implies exact membership. The fuzz target IS the laundering test: throw arbitrary crafted values at a closed-set rule and a numeric-range rule and assert nothing outside the declared set/range is ever released. A single crafted non-member that releases is a real laundering bug.
api:
  - func TestReleaseRule(t *testing.T)
  - func FuzzReleaseRule(f *testing.F)
behavior:
  - "SET MEMBERSHIP TABLE: rule := ReleaseRule{Kind: RuleSetMembership, Set: []string{\"restart\",\"isolate\",\"notify\"}}. Release(\"restart\")==true; Release(\"notify\")==true; Release(\"reboot\")==false; Release(\"RESTART\")==false (case); Release(\"restart \")==false (trailing space, no trim); Release(\"res\")==false (prefix/substring); Release(\"\")==false. Empty set ReleaseRule{Kind: RuleSetMembership}: Release(\"restart\")==false."
  - "SIGNED EQUALITY TABLE: rule := ReleaseRule{Kind: RuleSignedEquality, Signed: \"v1.2.3\"}. Release(\"v1.2.3\")==true; Release(\"v1.2.4\")==false; Release(\"v1.2.3 \")==false; Release(\"\")==false."
  - "SIGNED EMPTY GUARD: ReleaseRule{Kind: RuleSignedEquality}.Release(\"\")==false (an unconfigured empty Signed releases nothing)."
  - "NUMERIC RANGE TABLE: rule := ReleaseRule{Kind: RuleNumericRange, Min: 1, Max: 10}. Release(\"1\")==true; Release(\"5\")==true; Release(\"10\")==true; Release(\"0\")==false; Release(\"11\")==false; Release(\"-3\")==false; Release(\"abc\")==false; Release(\"5x\")==false; Release(\" 5\")==false; Release(\"\")==false. NON-CANONICAL spellings of in-range numbers must NOT release: Release(\"+5\")==false; Release(\"007\")==false; Release(\"05\")==false; Release(\"010\")==false. Empty range ReleaseRule{Kind: RuleNumericRange, Min: 10, Max: 1}: Release(\"5\")==false."
  - "KIND STRING: RuleSetMembership.String()==\"set_membership\"; RuleSignedEquality.String()==\"signed_equality\"; RuleNumericRange.String()==\"numeric_range\"; RuleKind(99).String()==\"unknown\"."
  - "PARSE ROUND-TRIP: for each of the three kinds, ParseRuleKind(k.String())==k with nil error. ParseRuleKind of the OLD spellings (\"set\"/\"signed-equality\"/\"numeric-range\"), of \"unknown\", of \"\", and of \" set_membership \" (whitespace-padded) each returns a non-nil error and the RuleKind(-1) sentinel; that sentinel releases nothing."
  - "FAIL CLOSED: ReleaseRule{Kind: RuleKind(99), Set: []string{\"restart\"}}.Release(\"restart\")==false (an unknown kind releases nothing)."
  - "FUZZ FuzzReleaseRule - the laundering test, with INDEPENDENT oracles (not the impl's own parser) for all three kinds. Seed with exact members and near-misses (\"restart\", \"restart \", \"RESTART\", \"5\", \"+5\", \"007\", \"010\", \"11\", \"\", \"v1.2.3\"). Body takes value string. (1) SET over members := []string{\"restart\",\"isolate\",\"notify\"}: isMember by exact == range; assert Release(value)==isMember. (2) RANGE {Min:1,Max:10}: build rangeMembers as a set of the CANONICAL strings strconv.FormatInt(n,10) for n in 1..10 (enumerated independently of Release); assert Release(value)==rangeMembers[value] - so \"007\"/\"+5\" (non-canonical) do NOT release. (3) SIGNED with a non-empty reference ref: assert Release(value)==(value==ref). Any mismatch is a laundering bug. (4) STRING/PARSE INVERSE: k, err := ParseRuleKind(value); if err==nil assert k.String()==value (parse only ever accepts a canonical spelling and round-trips it exactly); if err!=nil assert k==RuleKind(-1). No non-canonical string ever parses to a valid kind."
constraints: package main; standard library only (strconv, testing).
