name: Runner
role: component
intent: The runtime entry point (runtime, unit 5) - the stdio JSON-RPC transport plus the pipeline engine that turns an incident event into a gated, executed decision. Two cohesive parts. (A) Engine wires the whole runtime pipeline for one request - retrieve (kb) -> assemble (bind) -> gate (broker) -> fire-cleared (actuator) - behind a single Decide(ctx, event) method. (B) Serve is a fail-closed JSON-RPC 2.0 loop over stdio (newline-delimited JSON) that dispatches the "decide" method to any Decider. THE LOAD-BEARING PROPERTY: the Decider (the only thing that can cause a real effect, since it runs FireCleared) is invoked IFF a line is a well-formed "decide" request with a non-empty event - a malformed line, an unknown method, a bad params object, or an empty event NEVER reaches the pipeline and NEVER fires an actuator (complete mediation extended to the transport edge, inv 10; fail-closed, inv 8). The loop survives a bad line and keeps serving.
api:
  - "type Retriever interface { Retrieve(ctx context.Context, query string, k int) ([]kb.Doc, error) }"
  - "type Gate interface { Decide(ctx context.Context, req model.Request) (broker.Decision, error) }"
  - "type Engine struct { Instruction string; Store Retriever; K int; Gate Gate; Registry actuator.Registry }"
  - "type ActionView struct { Kind string; Ref string; Verdict string }"
  - "type DecideResult struct { Verdict string; Value string; Model string; Cleared []ActionView; Recommend []ActionView; Denied []ActionView; Events []stag.ReleaseEvent; Fired []actuator.Result; Fault string; EgressErr string }"
  - func (e Engine) Decide(ctx context.Context, event string) (DecideResult, error)
  - "type Decider interface { Decide(ctx context.Context, event string) (DecideResult, error) }"
  - func Serve(ctx context.Context, in io.Reader, out io.Writer, d Decider) error
concept: the runtime pipeline (retrieve/assemble/gate/fire) behind one method; the fail-closed stdio JSON-RPC transport; the Decider is invoked iff the request is well-formed and names a non-empty event.
behavior:
  - "ENGINE PIPELINE: Engine.Decide(ctx, event) with a NON-EMPTY event: (1) calls Store.Retrieve(ctx, event, e.K) - the event text IS the retrieval query; (2) calls bind.Assemble(e.Instruction, event, docs) to build the model.Request - so System is the trusted instruction and the event+docs are untrusted Input (the trust position is preserved through the runner); (3) calls e.Gate.Decide(ctx, req); (4) on gate success calls actuator.FireCleared(ctx, e.Registry, dec). It returns a DecideResult carrying the verdict string, the proposal value+model, the cleared/recommend/denied actions as legible ActionViews (Verdict via .String()), the release Events, and the Fired actuator Results."
  - "ENGINE FAIL-CLOSED: Engine.Decide with an EMPTY event returns a non-nil error and does NOT call Retrieve, Gate, or FireCleared (nothing fires). If Retrieve returns an error, Decide returns it and does NOT gate or fire. If Gate.Decide returns an error, Decide returns it and does NOT fire (FireCleared is never reached) - the fail-closed path executes no effect. On every error path the returned DecideResult is the zero value and no actuator fired."
  - "ENGINE FIRES ONLY CLEARED: FireCleared is called with the gate's Decision, so it fires only dec.Cleared - never dec.Denied or dec.Recommend - even end-to-end through the runner. The Fired list in the result contains exactly the cleared actions' Results."
  - "SERVE - VALID DECIDE: Serve reads newline-delimited JSON from in. For a line {\"jsonrpc\":\"2.0\",\"id\":<id>,\"method\":\"decide\",\"params\":{\"event\":\"<text>\"}} with non-empty event, it calls d.Decide(ctx, text) exactly once and writes one response line {\"jsonrpc\":\"2.0\",\"id\":<id>,\"result\":<DecideResult>}; the id is echoed verbatim. Each response is a single line (json.Encoder newline framing)."
  - "SERVE - FAIL-CLOSED DISPATCH: for a line that is not valid JSON, Serve writes an error response with code -32700 (parse) and does NOT call the Decider. For a valid JSON object whose jsonrpc != \"2.0\": code -32600. For method != \"decide\": code -32601 (method not found). For params that do not decode or whose event is empty: code -32602 (invalid params). In EVERY one of these cases the Decider is NOT invoked and NO actuator can fire. If the Decider returns an error, Serve writes code -32603 (internal) with the error message and the matching id. Every error response has jsonrpc \"2.0\"; a parse-error response carries a null id."
  - "SERVE - LOOP SURVIVES A BAD LINE: a malformed line followed by a well-formed decide line yields TWO response lines - an error for the first and a result for the second; one bad request does not stop the server. Blank lines are skipped (no response). Serve returns nil at EOF and never panics on any input."
  - "SERVE - DETERMINISTIC FRAMING: the same input stream with the same Decider yields byte-identical output."
constraints: package runner at workspaces/stag/runner (public; import path github.com/scanset/StAG/runner). Depends on the kb, bind, broker, actuator, model packages, the stag root (ReleaseEvent, Verdict.String), and stdlib (context, io, bufio, bytes, encoding/json, errors, fmt). broker.Broker satisfies Gate and kb.*MemStore satisfies Retriever by structural typing; Engine satisfies Decider. No network in this package; the transport is pure framing over injected dependencies.
