name: RunnerTest
role: test
intent: Verify the runtime pipeline wiring and the fail-closed stdio JSON-RPC transport. Prove the Engine wires retrieve->assemble->gate->fire in order, preserves the trust position (System==instruction) through the runner, fires ONLY cleared actions end-to-end, and fails closed (no retrieve/gate/fire on empty event; no fire on gate error). Prove Serve dispatches "decide" to the Decider IFF the line is a well-formed decide request with a non-empty event, returns fail-closed JSON-RPC errors otherwise, never calls the Decider on a malformed/unknown/empty request, survives a bad line, and never panics. A fuzz drives arbitrary byte streams through Serve against a spy Decider and asserts the Decider is invoked only for well-formed decide requests.
api:
  - func TestEnginePipeline(t *testing.T)
  - func TestEngineFiresOnlyCleared(t *testing.T)
  - func TestEngineFailClosed(t *testing.T)
  - func TestServeValidDecide(t *testing.T)
  - func TestServeFailClosedDispatch(t *testing.T)
  - func TestServeSurvivesBadLine(t *testing.T)
  - func FuzzServeDispatch(f *testing.F)
prelude: "A fakeRetriever records the (query,k) it was called with and returns a fixed doc slice (or a configured error). A fakeGate records the model.Request it received and returns a configured broker.Decision (or an error); it lets a test assert System==instruction and inspect Cleared/Denied. A spy actuator records each Fire. A spyDecider implements Decider, recording every event passed to Decide and returning a fixed DecideResult (or a configured error), so a transport test can assert exactly when the pipeline was reached."
behavior:
  - "ENGINE PIPELINE: an Engine with Instruction \"choose a label\", a fakeRetriever returning one doc, K=3, a fakeGate returning a Decision{Verdict:Allow, Proposal:{Value:\"restart_service\"}, Cleared:[{Ref:\"svc\"}]}, and a Registry binding a spy to \"svc\". Engine.Decide(ctx, \"cpu 98%\") returns a DecideResult with Verdict \"allow\", Value \"restart_service\", one Cleared ActionView (Ref \"svc\"), and one Fired result. ASSERT the fakeRetriever saw query \"cpu 98%\" and k 3; ASSERT the fakeGate's received request has System == \"choose a label\" and the event text present in Input (trust position preserved); ASSERT the spy fired once for \"svc\"."
  - "ENGINE FIRES ONLY CLEARED: a fakeGate returning Cleared:[{Ref:\"a\"}] and Denied:[{Ref:\"b\"}] with a Registry binding a spy to BOTH a and b. Engine.Decide fires only \"a\"; the spy log is exactly [a]; the DecideResult.Denied contains b but nothing denied fired."
  - "ENGINE FAIL-CLOSED: (empty event) Engine.Decide(ctx, \"\") returns a non-nil error, a zero DecideResult, and the fakeRetriever/fakeGate/spy were NEVER called. (retrieve error) a fakeRetriever returning an error -> Decide returns the error, gate not called, nothing fired. (gate error) a fakeGate returning an error -> Decide returns the error and the spy NEVER fired (FireCleared not reached)."
  - "SERVE VALID DECIDE: Serve over an in-process pipe (bytes.Reader in, bytes.Buffer out) with a spyDecider. Input line {\"jsonrpc\":\"2.0\",\"id\":7,\"method\":\"decide\",\"params\":{\"event\":\"disk full\"}}. ASSERT spyDecider.Decide was called once with \"disk full\"; the output is one JSON line with id 7 and a result field; jsonrpc \"2.0\"."
  - "SERVE FAIL-CLOSED DISPATCH: for each of - a non-JSON line \"{not json\"; a line with jsonrpc \"1.0\"; method \"delete_everything\"; params event \"\" - Serve writes an error response with the expected code (-32700, -32600, -32601, -32602) and the spyDecider is NEVER called. A spyDecider configured to return an error yields a -32603 response with the matching id. Every response has jsonrpc \"2.0\"; the parse-error response has a null id."
  - "SERVE SURVIVES A BAD LINE: input of a bad line \"garbage\" then a good decide line. Output is two response lines: the first an error, the second a result whose id matches the good request; the spyDecider was called exactly once (for the good line). Blank lines produce no response. Serve returns nil at EOF."
  - "FUZZ FuzzServeDispatch - transport complete mediation. Seed with a valid decide request, a malformed line, an unknown method, an empty-event request, and multi-line inputs. In the body, run Serve(ctx, bytes.NewReader(input), &out, spy) where spy NEVER errors and records each event. ASSERT: (1) Serve returns nil and never panics; (2) every event the spy recorded came from a line that JSON-decodes to a well-formed decide request with a non-empty event - the spy is invoked ONLY for such lines (parse via the same rules and count expected calls; the number and payloads of spy calls equal the well-formed-decide lines in order); (3) every non-blank output line is valid JSON with jsonrpc \"2.0\"; (4) a second identical run produces byte-identical output (determinism)."
constraints: package runner_test (external test); depends on the runner, kb, bind, broker, model, actuator packages, the stag root, and stdlib (context, bytes, encoding/json, errors, strings, testing). No network; the fakes stand in for the store, gate, and actuators.
