name: SinkGate
role: component
intent: The ABAC decision at the sink (U3). Given a value's TrustClass (U1), a sink's declared sensitivity (authoritative | benign), and whether a release has cleared this specific crossing, return a Verdict (U2). This is the gate that protects authoritative sinks - the protected resource (invariant 5). It reads the trust label as ONE attribute (invariant 4: IFC computes, ABAC decides) and is fail-safe (invariant 8): a value that is not authoritative never silently reaches an authoritative sink without a release. The declassifier (U4 evaluates the release rule, U6 records the crossing) is the only path by which a non-authoritative value crosses; U3 consumes that result as the `released` flag but does NOT evaluate release rules or inspect content itself. CEILING: the gate is only as correct as the TrustClass label it is handed - it decides from that label, it cannot validate it. A binder propagation bug (over- or under-taint) is a silent authorization failure the gate cannot catch; trust shifts to the IFC feeding it (Planning/05 open problem). The binder's Join propagation (U1) is small and testable, but the dependency is real and must be owned upstream.
api:
  - type SinkSensitivity int
  - const ( SinkBenign SinkSensitivity = iota; SinkAuthoritative )
  - func (s SinkSensitivity) String() string
  - func ParseSinkSensitivity(s string) (SinkSensitivity, error)
  - func GateSink(subject TrustClass, sink SinkSensitivity, released bool) Verdict
behavior:
  - "SENSITIVITY STRING: SinkBenign -> \"benign\", SinkAuthoritative -> \"authoritative\". String on any value outside the set returns \"unknown\". ParseSinkSensitivity is the inverse for the two defined names and returns a non-nil error for anything else (including \"unknown\"). ROUND-TRIP: for each defined sensitivity s, ParseSinkSensitivity(s.String())==s with a nil error."
  - "BENIGN SINK is not release-gated: GateSink(anySubject, SinkBenign, anyReleased)==Allow. A benign sink is recorded but its taint does not gate, so the verdict is Allow regardless of the subject's class or the release flag."
  - "AUTHORITATIVE SINK, RELEASED: GateSink(anySubject, SinkAuthoritative, true)==Allow. A true `released` flag means the declassifier cleared THIS specific crossing (U4 judged the rule, U6 records it); the gate trusts the flag and allows. U3 does not re-judge the release."
  - "AUTHORITATIVE SINK, NOT RELEASED - the fail-safe core. GateSink(Authoritative, SinkAuthoritative, false)==Allow (an authoritative value may reach an authoritative field). Every non-authoritative subject is denied unless released: GateSink(Untrusted, SinkAuthoritative, false)==Deny AND GateSink(Caller, SinkAuthoritative, false)==Deny. RATIFIED (2026-07-01): Caller is deny-unless-released, NOT escalate - the declassifier (a recorded release) is the sole crossing path for any non-authoritative value; there is no human-approval side channel at the gate. Only an authoritative subject (or released==true) yields Allow here."
  - "SEVERED / UNKNOWN LABEL FAILS CLOSED (invariant 8): for an authoritative sink with released==false, a subject TrustClass outside {Untrusted, Caller, Authoritative} returns Deny."
  - "UNREGISTERED SINK IS REFUSED (invariant 10, complete mediation): a SinkSensitivity outside {SinkBenign, SinkAuthoritative} returns Deny - an unknown sink is refused, never silently allowed, and is checked before the subject class."
  - "THE LOAD-BEARING PROPERTY (fail-safe, invariant 8): for an authoritative sink with released==false, GateSink returns Allow ONLY when subject==Authoritative. Equivalently, no non-authoritative value ever reaches an authoritative sink at Allow without a release. This is the U3-level shadow of the whole-product invariant that U7 (RecipeEval, deferred / not yet built) will prove by composing this gate verdict with a recorded ReleaseEvent through the bind graph; U3 alone proves only the verdict half."
constraints: package main; standard library only. Depends on TrustClass (U1: Untrusted<Caller<Authoritative) and Verdict (U2: Allow, Escalate, Deny), both in the same flat package.
