// Command stag-proxy is the standing gating MCP server — the front door an agent host
// connects to (Planning/24). It is an MCP SERVER to the agent and an MCP CLIENT to the
// real downstream server, with the deterministic gate in the middle: every tool call is
// gated, cleared calls forward to the downstream, denied ones return a gate error and
// never reach it. It holds NO model and NO keys — only the gate, the routes, and the
// audit log. Config (routes + downstream) comes from the same store the console manages.
//
// v1: single downstream, served over stdio (the agent spawns this and speaks MCP over its
// stdio). Routes are resolved once at startup. Streamable HTTP + session->recipe is next.
package main

// file-kw: cmd gate mcp gating proxy daemon session-to-recipe stdio streamable-http live-vs-ready fail-closed dispatch-role

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sync"
	"sync/atomic"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/scanset/stoagraph/stoa-kernel/stag/auth"
	"github.com/scanset/stoagraph/stoa-kernel/stag/egress"
	"github.com/scanset/stoagraph/stoa-kernel/stag/notify"
	"github.com/scanset/stoagraph/stoa-kernel/stag/provider"
	"github.com/scanset/stoagraph/stoa-kernel/stag/proxy"
	"github.com/scanset/stoagraph/stoa-kernel/stag/proxy/mcpgate"
	"github.com/scanset/stoagraph/stoa-kernel/stag/proxy/sessiond"
	"github.com/scanset/stoagraph/stoa-kernel/stag/recipestore"
	"github.com/scanset/stoagraph/stoa-kernel/stag/router"
	"github.com/scanset/stoagraph/stoa-kernel/stag/store"
)

// readRecorder returns a best-effort audit sink for READ crossings (Planning/30): one JSON line per
// resources/read on a context provider. Reads are label+record, not release, so this is a plain
// append log — separate from the hash-chained decisions log (which is only for cleared ACT crossings).
// Concurrent sessions may read at once, so the write is mutex-guarded.
func readRecorder(w io.Writer) func(context.Context, provider.ReadEvent) {
	var mu sync.Mutex
	return func(_ context.Context, ev provider.ReadEvent) {
		rec := struct {
			Kind string    `json:"kind"`
			Time time.Time `json:"ts"`
			provider.ReadEvent
		}{Kind: "read", Time: time.Now(), ReadEvent: ev}
		b, err := json.Marshal(rec)
		if err != nil {
			return
		}
		mu.Lock()
		defer mu.Unlock()
		_, _ = w.Write(append(b, '\n'))
	}
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	storePath := flag.String("store", "data/config.db", "SQLite config store (routes, downstream servers)")
	recipesDir := flag.String("recipes-dir", "data/recipes", "recipe store (shared with stag-serve)")
	logPath := flag.String("log", "data/decisions.jsonl", "hash-chained egress log for cleared crossings")
	readLogPath := flag.String("read-log", "data/reads.jsonl", "audit log for READ crossings (context provider reads)")
	downstream := flag.String("downstream", "", "name of the mcp_server to proxy (default: first enabled)")
	approvalWebhook := flag.String("approval-webhook", os.Getenv("STAG_APPROVAL_WEBHOOK"), "optional URL POSTed a notice when the gate escalates a fresh action")
	httpAddr := flag.String("http", "", "run as a standing daemon on this address (session→recipe over streamable HTTP); empty = stdio mode")
	tokensPath := flag.String("tokens", "data/control.tokens", "control-plane role tokens (generated by stag-serve); POST /sessions requires `dispatch`")
	devNoAuth := flag.Bool("dev-no-auth", false, "DANGER: disable control-plane auth on POST /sessions (local dev only)")
	flag.Parse()

	// stdio carries the MCP protocol on stdout; logs go to stderr.
	log.SetOutput(os.Stderr)
	ctx := context.Background()

	st, err := store.Open(*storePath)
	die(err)
	defer st.Close()
	recipes := recipestore.Store{Dir: *recipesDir}

	// egress sink (SHARED): resume the hash chain; refuse to append to a tampered log. One process
	// owns this one log — in daemon mode every session writes through it, so there is no per-run
	// fork (the v1 bug where each spawned proxy forked the shared log).
	prev := egress.VerifyResult{}
	if b, rerr := os.ReadFile(*logPath); rerr == nil && len(b) > 0 {
		var verr error
		if prev, verr = egress.Verify(bytes.NewReader(b)); verr != nil {
			die(fmt.Errorf("egress log %s is tampered, refusing to start: %w", *logPath, verr))
		}
	}
	f, err := os.OpenFile(*logPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	die(err)
	defer f.Close()
	sink := egress.ResumeJSONLSink(f, prev.Head, prev.Count)

	// Stage 5: the config store is the approval queue; an escalate records a pending row (+ webhook),
	// an approved retry releases. The proxy mints NO tokens (stag-serve holds the signing key).
	onEscalate := notify.Webhook(*approvalWebhook)

	if *httpAddr != "" {
		// DAEMON (v2): session→recipe over streamable HTTP. Sessions bring their OWN routes — the
		// trusted dispatcher binds them via POST /sessions and the untrusted agent connects to
		// /mcp/<token>. No global route table; the agent cannot choose its own recipe.
		rf, err := os.OpenFile(*readLogPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
		die(err)
		defer rf.Close()
		// CONTROL-PLANE AUTH (Planning/31): the daemon only CONSUMES tokens — it must never invent a
		// secret nobody else knows, so a missing tokens file is fatal (start stag-serve first, or set
		// STAG_DISPATCH_TOKEN). POST /sessions then requires the `dispatch` role.
		var an *auth.Authenticator
		if *devNoAuth {
			log.Printf("!!! CONTROL PLANE UNAUTHENTICATED (-dev-no-auth) — anyone can bind a session to ANY recipe. Local dev only.")
			an = &auth.Authenticator{Disabled: true}
		} else {
			tokens, aerr := auth.Load(*tokensPath)
			die(aerr)
			// The daemon guards exactly one thing — POST /sessions — with `dispatch`. It has no use for
			// admin/approve/operator, so it does not keep them. Least privilege, even inside the gate.
			an = &auth.Authenticator{Tokens: tokens.Only(auth.RoleDispatch)}
		}
		// LIVE vs READY. Serve /health immediately, but connect the downstream in the BACKGROUND: a
		// fresh instance has none registered yet, and a container that blocked here would never answer
		// its probe and be killed forever for doing the right thing.
		//
		// Until a downstream is connected the gate is LIVE but NOT READY, and it says so with 503 —
		// it does not bind sessions. That is fail-closed: a gate with nothing to mediate must not
		// pretend it is mediating.
		var ready atomic.Pointer[http.Handler]
		reg := sessiond.NewRegistry()

		go func() {
			srv, session, tools := awaitDownstream(ctx, st, *downstream)
			defer session.Close()
			h := sessiond.Handler(reg, sessiond.Deps{
				Sink: sink, Approvals: st, OnEscalate: onEscalate,
				Downstream: session, Tools: tools, LoadRecipe: recipes.Get,
				RecordRead: readRecorder(rf),
				Auth:       an,
			})
			ready.Store(&h)
			log.Printf("downstream %q connected (%s: %s, %d tools) — POST /sessions to bind, connect /mcp/<token>",
				srv.Name, srv.Transport, srv.Target, len(tools))
			select {} // the connection is held for the process lifetime
		}()

		mux := http.NewServeMux()
		mux.HandleFunc("GET /health", func(w http.ResponseWriter, _ *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			fmt.Fprintf(w, `{"ok":true,"ready":%t}`+"\n", ready.Load() != nil)
		})
		mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
			h := ready.Load()
			if h == nil {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusServiceUnavailable)
				fmt.Fprintln(w, `{"error":"gate not ready: no downstream MCP server connected yet"}`)
				return
			}
			(*h).ServeHTTP(w, r)
		})

		log.Printf("stag-proxy DAEMON on %s — waiting for a downstream; /health is live, /sessions 503s until ready",
			*httpAddr)
		die(http.ListenAndServe(*httpAddr, mux))
		return
	}

	// STDIO (v1): an agent host spawned us expecting a working gate RIGHT NOW, so a missing or
	// unreachable downstream is fatal here — there is nobody to wait for and nothing to serve.
	srv, err := pickDownstream(ctx, st, *downstream)
	die(err)
	session, tools, err := mcpgate.Connect(ctx, srv.Transport, srv.Target,
		mcpgate.Auth{Scheme: srv.AuthScheme, Header: srv.AuthHeader, Credential: srv.Credential()})
	die(err)
	defer session.Close()

	// The global route table from the store; every connection shares it.
	routes, err := st.ListRoutes(ctx)
	die(err)
	specs := make([]router.Spec, 0, len(routes))
	for _, rt := range routes {
		specs = append(specs, router.Spec{Tool: rt.Tool, Recipe: rt.Recipe, GateArg: rt.GateArg})
	}
	resolved := router.Build(specs, recipes.Get)
	for _, re := range resolved.Errors {
		log.Printf("route %q -> %q unresolved: %s (tool will be denied)", re.Tool, re.Recipe, re.Err)
	}
	gate := proxy.Gate{Routes: resolved.Router, Sink: sink, Approvals: st, OnEscalate: onEscalate}
	log.Printf("stag-proxy: downstream %q (%s: %s) — %d tool(s), %d route(s); serving gated MCP over stdio",
		srv.Name, srv.Transport, srv.Target, len(tools), len(routes))
	// stdio v1 is tools-only (no session-bound READ channel); the daemon serves context resources.
	gatingSrv := mcpgate.NewGatingServer(gate, session, tools, mcpgate.ReadChannel{})
	die(gatingSrv.Run(ctx, &mcp.StdioTransport{}))
}

// awaitDownstream blocks until a downstream MCP server is registered AND reachable, then connects.
// It re-reads the config store each attempt, so registering a server from the console (or an example's
// setup) is picked up without a restart. Nothing is served until this succeeds — a gate with no
// downstream has nothing to mediate, and it must never fall open while it waits.
func awaitDownstream(ctx context.Context, st *store.Store, name string) (store.MCPServer, *mcp.ClientSession, []*mcp.Tool) {
	const retry = 5 * time.Second
	for attempt := 0; ; attempt++ {
		srv, err := pickDownstream(ctx, st, name)
		if err != nil {
			if attempt == 0 {
				log.Printf("no downstream MCP server registered yet — waiting. Register one in the console (Adapters), or run an example's setup.sh. Retrying every %s.", retry)
			}
			time.Sleep(retry)
			continue
		}
		session, tools, cerr := mcpgate.Connect(ctx, srv.Transport, srv.Target,
			mcpgate.Auth{Scheme: srv.AuthScheme, Header: srv.AuthHeader, Credential: srv.Credential()})
		if cerr != nil {
			log.Printf("downstream %q (%s: %s) unreachable: %v — retrying in %s", srv.Name, srv.Transport, srv.Target, cerr, retry)
			time.Sleep(retry)
			continue
		}
		return srv, session, tools
	}
}

// pickDownstream returns the named mcp_server, or the first enabled one if unnamed.
func pickDownstream(ctx context.Context, st *store.Store, name string) (store.MCPServer, error) {
	if name != "" {
		return st.GetMCPServer(ctx, name)
	}
	servers, err := st.ListMCPServers(ctx)
	if err != nil {
		return store.MCPServer{}, err
	}
	for _, s := range servers {
		if s.Enabled {
			return s, nil
		}
	}
	return store.MCPServer{}, fmt.Errorf("stag-proxy: no enabled mcp_server configured (add one in the console)")
}
