// Command harness-serve is the ORCHESTRATOR's API: connect models, author the event map, and
// dispatch an event through the gate to a governed agent. It runs the agent tool-use loop and
// streams the transcript (model proposals + gate verdicts) as SSE.
//
// This is where the model API KEYS live. The gate (stag) holds none — that asymmetry is the
// product's central claim, and it is enforced, not merely intended: see architecture_test.go, which
// fails the build if any gate package so much as imports orchestrator code.
//
// API only. The console is the Next.js app in frontend/, which unifies BOTH backends' surfaces.
package main

// file-kw: cmd orchestrator api models keys dispatch event-map sse operator-role never-approve cors

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"

	"github.com/scanset/stoagraph/stoa-kernel/harness/agent"
	"github.com/scanset/stoagraph/stoa-kernel/harness/dispatch"
	"github.com/scanset/stoagraph/stoa-kernel/harness/ingress"
	"github.com/scanset/stoagraph/stoa-kernel/harness/store"
	"github.com/scanset/stoagraph/stoa-kernel/stag/auth"
	"github.com/scanset/stoagraph/stoa-kernel/stag/egress"
)

type Server struct {
	models    *store.Store
	approvals string // stag-serve base URL (approval loop + the recipe/route catalog for dispatch)
	eventMap  string // path to the user-authored event map (event → recipe definitions)
	daemon    string // stag-proxy DAEMON base URL (session→recipe; where dispatch binds sessions)
	// The READ channel is now served BY THE GATE (Planning/30): dispatch reads stag://context/*
	// resources from the session, so the embedder/KB live in a downstream provider, not here.

	// stagToken is the control-plane `dispatch` secret this orchestrator PRESENTS to stag (Planning/31):
	// bind sessions, read the catalog, poll approvals. It is NOT the `approve` token — the harness can
	// never approve its own escalations.
	stagToken string
	// auth guards harness-serve's OWN API (models hold provider API keys; dispatch/run spend them and
	// act on the world) with the `operator` role. Nil fails closed.
	auth *auth.Authenticator

	// ingressChain is the hash-chained ingress log (Planning/32): every event that arrives at the
	// webhook front door is recorded, dispatched or dropped. Nil => the webhook endpoint is disabled.
	ingressChain *egress.Chain[ingress.Record]
	// ingressSecret is the shared HMAC secret the generic webhook adapter verifies deliveries against.
	// Empty => the endpoint accepts events but can never ATTRIBUTE them (all unattributed).
	ingressSecret []byte
	// ingressModel is the proposer model a webhook-dispatched event runs its governed agent loop with.
	// Empty => the webhook front door resolves + records but does not run the loop (resolve-only).
	ingressModel string
	// runEvent launches the governed run for a matched webhook event (fire-and-forget). Set only when
	// an ingress model is configured; nil => resolve-only. A seam so tests can observe the trigger
	// without a live daemon.
	runEvent func(dispatch.Decision, dispatch.Event, ingress.Envelope)
}

func main() {
	addr := flag.String("addr", ":8090", "listen address")
	modelsPath := flag.String("models", "config/models.json", "model config file (JSON)")
	approvalsURL := flag.String("approvals-url", "http://localhost:8080", "stag-serve base URL (approval loop + dispatch catalog); empty disables the approval loop")
	eventMapPath := flag.String("event-map", "config/event_map.json", "event map (event → recipe definitions) for dispatch")
	daemonURL := flag.String("daemon-url", "http://localhost:8091", "stag-proxy daemon base URL (session→recipe) for dispatch")
	tokensPath := flag.String("tokens", "data/control.tokens", "control-plane role tokens (generated by stag-serve): this orchestrator PRESENTS `dispatch` and REQUIRES `operator` on its own API")
	ingressLog := flag.String("ingress-log", "", "hash-chained ingress log for the webhook front door (empty disables POST /api/ingress/{source})")
	ingressModel := flag.String("ingress-model", "", "proposer model a webhook-dispatched event runs its governed agent loop with (empty = resolve+record only)")
	devNoAuth := flag.Bool("dev-no-auth", false, "DANGER: disable auth on this API and send no token to stag (local dev only)")
	flag.Parse()

	// CONTROL-PLANE AUTH (Planning/31). harness-serve is a CONSUMER of tokens: it presents `dispatch`
	// to stag (bind/catalog/poll) and requires `operator` on its own API. It never holds `approve` —
	// an orchestrator that could approve its own escalations would make the human gate decorative.
	s := &Server{
		models: store.Open(*modelsPath), approvals: *approvalsURL, eventMap: *eventMapPath, daemon: *daemonURL,
	}
	if *devNoAuth {
		log.Printf("!!! CONTROL PLANE UNAUTHENTICATED (-dev-no-auth) — this API is wide open and no token is sent to stag. Local dev only.")
		s.auth = &auth.Authenticator{Disabled: true}
	} else {
		tokens, aerr := auth.Load(*tokensPath)
		if aerr != nil {
			log.Fatalf("harness-serve: %v", aerr)
		}
		// NARROW IMMEDIATELY. The orchestrator is entitled to exactly two secrets: `dispatch` (bind
		// sessions + poll the gate) and `operator` (guard its own API). It must NEVER retain `approve`.
		//
		// Enforcing the split only at the gate's HTTP layer is not enough: a compromised orchestrator
		// would not send `dispatch` to an approve route and politely accept the 401 — it would send the
		// `approve` token it was holding, because the shared tokens file contains all four. Holding a
		// secret you never use is still holding it. In a container this file is not mounted at all and
		// these two arrive via env; here we drop the rest on the floor.
		tokens = tokens.Only(auth.RoleDispatch, auth.RoleOperator)

		s.stagToken = tokens.Dispatch
		s.auth = &auth.Authenticator{Tokens: tokens}
		if s.stagToken == "" {
			log.Fatal("harness-serve: no `dispatch` token — the orchestrator cannot bind sessions on the gate")
		}
	}
	operator := s.auth.Guard(auth.RoleOperator)

	// INGRESS front door (Planning/32). A hash-chained log of every arrival; the webhook endpoint is
	// authenticated by the delivery HMAC (channel attribution), NOT the operator bearer — external
	// sources do not hold it. Verify any existing chain before appending (refuse a tampered history).
	if *ingressLog != "" {
		iprev := egress.VerifyResult{}
		if b, rerr := os.ReadFile(*ingressLog); rerr == nil && len(b) > 0 {
			var verr error
			if iprev, verr = egress.VerifyChain[ingress.Record](bytes.NewReader(b)); verr != nil {
				log.Fatalf("harness-serve: ingress log %s failed verification (tamper?): %v", *ingressLog, verr)
			}
		}
		f, ferr := os.OpenFile(*ingressLog, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
		if ferr != nil {
			log.Fatalf("harness-serve: open ingress log: %v", ferr)
		}
		defer f.Close()
		s.ingressChain = egress.ResumeChain[ingress.Record](f, iprev.Head, iprev.Count)
		s.ingressSecret = []byte(os.Getenv("STAG_INGRESS_SECRET"))
		s.ingressModel = *ingressModel
		if s.ingressModel != "" {
			s.runEvent = s.runIngressEvent // a model is configured -> webhook events RUN the governed loop
		}
		log.Printf("ingress front door: POST /api/ingress/{source} -> %s (HMAC %s)", *ingressLog,
			map[bool]string{true: "on", false: "OFF — set STAG_INGRESS_SECRET to attribute"}[len(s.ingressSecret) > 0])
	}

	mux := http.NewServeMux()
	// API-ONLY. The console is the Next.js app (frontend/), which serves BOTH backends' surfaces —
	// the embedded index.html that used to live here is retired (Planning/26: one console, two
	// backends). Liveness stays open for container probes.
	mux.HandleFunc("GET /health", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]any{"ok": true})
	})
	// Everything below is the operator's control plane: models hold provider API KEYS, and
	// dispatch/run SPEND them and act on the real world. `operator` role required.
	mux.HandleFunc("GET /api/models", operator(s.listModels))
	mux.HandleFunc("POST /api/models", operator(s.putModel))
	mux.HandleFunc("DELETE /api/models/{name}", operator(s.deleteModel))
	mux.HandleFunc("POST /api/run", operator(s.run))
	mux.HandleFunc("POST /api/dispatch", operator(s.dispatch))
	mux.HandleFunc("GET /api/event-map", operator(s.getEventMap))
	mux.HandleFunc("POST /api/event-map", operator(s.putEventMap))
	// The webhook front door: authenticated by the delivery HMAC, not the operator bearer. Registered
	// only when --ingress-log is set (s.webhook guards on a nil chain too).
	mux.HandleFunc("POST /api/ingress/{source}", s.webhook)

	log.Printf("harness-serve on %s — models in %s (API only; console is the Next.js app)", *addr, *modelsPath)
	log.Fatal(http.ListenAndServe(*addr, cors(mux)))
}

// cors lets the console (a different origin, e.g. :3000) call this API. Authorization MUST be an
// allowed header or the browser can never present the `operator` bearer token (Planning/31).
func cors(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// --- model config (no raw key ever leaves) ---

type modelView struct {
	Name       string `json:"name"`
	Kind       string `json:"kind"`
	BaseURL    string `json:"baseUrl"`
	Model      string `json:"model"`
	APIKeyEnv  string `json:"apiKeyEnv"`
	KeyPresent bool   `json:"keyPresent"`
	KeyHint    string `json:"keyHint,omitempty"`
}

func view(m store.Model) modelView {
	hint := ""
	if m.APIKey != "" {
		if len(m.APIKey) > 4 {
			hint = "…" + m.APIKey[len(m.APIKey)-4:]
		} else {
			hint = "…"
		}
	}
	return modelView{m.Name, m.Kind, m.BaseURL, m.Model, m.APIKeyEnv, m.Key() != "", hint}
}

func (s *Server) listModels(w http.ResponseWriter, _ *http.Request) {
	ms, err := s.models.List()
	if err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	out := make([]modelView, 0, len(ms))
	for _, m := range ms {
		out = append(out, view(m))
	}
	writeJSON(w, 200, out)
}

func (s *Server) putModel(w http.ResponseWriter, r *http.Request) {
	var req store.Model
	if json.NewDecoder(r.Body).Decode(&req) != nil || req.Name == "" {
		writeErr(w, 400, "model needs a name")
		return
	}
	if req.Kind != "claude" && req.Kind != "openai" {
		writeErr(w, 400, `kind must be "claude" or "openai"`)
		return
	}
	if req.Model == "" {
		writeErr(w, 400, "model id is required")
		return
	}
	if req.Kind == "openai" && req.BaseURL == "" {
		writeErr(w, 400, "baseUrl is required for an openai-compatible model")
		return
	}
	if err := s.models.Put(req); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	writeJSON(w, 200, view(req))
}

func (s *Server) deleteModel(w http.ResponseWriter, r *http.Request) {
	if err := s.models.Delete(r.PathValue("name")); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	writeJSON(w, 200, map[string]any{"deleted": r.PathValue("name")})
}

// --- the run: simulate an event -> forward through stag-proxy -> stream the gated transcript ---

func (s *Server) run(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Model    string `json:"model"`
		Proxy    string `json:"proxy"`
		System   string `json:"system"`
		Input    string `json:"input"`
		MaxTurns int    `json:"maxTurns"`
	}
	if json.NewDecoder(r.Body).Decode(&req) != nil {
		writeErr(w, 400, "bad request")
		return
	}
	m, ok, err := s.models.Get(req.Model)
	if err != nil || !ok {
		writeErr(w, 404, "model not found")
		return
	}
	if req.Proxy == "" || req.Input == "" {
		writeErr(w, 400, "need a stag-proxy command and an input")
		return
	}

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	flusher, _ := w.(http.Flusher)
	emit := func(e agent.Event) {
		b, _ := json.Marshal(e)
		fmt.Fprintf(w, "data: %s\n\n", b)
		if flusher != nil {
			flusher.Flush()
		}
	}

	ctx := r.Context()
	sess, tools, err := agent.Connect(ctx, req.Proxy)
	if err != nil {
		emit(agent.Event{Kind: "error", Text: "connect stag-proxy: " + err.Error()})
		return
	}
	defer sess.Close()
	names := make([]string, len(tools))
	for i, t := range tools {
		names[i] = t.Name
	}
	emit(agent.Event{Kind: "text", Text: fmt.Sprintf("connected to stag-proxy — %d gated tool(s): %v", len(tools), names)})

	model, err := buildModel(m, req.System, req.Input, tools)
	if err != nil {
		emit(agent.Event{Kind: "error", Text: err.Error()})
		return
	}
	maxTurns := req.MaxTurns
	if maxTurns <= 0 {
		maxTurns = 6
	}
	agent.Run(ctx, model, sess, maxTurns, agent.NewApprovalConfig(s.approvals, s.stagToken), emit)
}

func buildModel(m store.Model, system, input string, tools []agent.Tool) (agent.ToolModel, error) {
	key := m.Key()
	if key == "" {
		return nil, fmt.Errorf("model %q has no usable key (set one on the Models tab or a set env var)", m.Name)
	}
	switch m.Kind {
	case "claude":
		return agent.NewClaude(key, m.Model, m.BaseURL, system, input, tools), nil
	case "openai":
		return agent.NewOpenAI(key, m.Model, m.BaseURL, system, input, tools), nil
	default:
		return nil, fmt.Errorf("unknown model kind %q", m.Kind)
	}
}

// --- helpers ---

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(v)
}
func writeErr(w http.ResponseWriter, code int, msg string) {
	writeJSON(w, code, map[string]string{"error": msg})
}
