#!/usr/bin/env bash
# tools/hygiene.sh — repo invariants that fail SILENTLY if nobody checks them.
#
# Every check here exists because the bug it catches actually happened, and none of them announce
# themselves: the build keeps working locally while the REPO is wrong. Run in CI.
#
#   1. no source is ignored      — a `/stoa-kernel/harness` binary pattern once matched the
#                                  ORCHESTRATOR'S SOURCE DIRECTORY and silently swallowed 19 .go files.
#                                  `go build` still worked; only a fresh clone would have been broken.
#   2. no secret is tracked      — .gitignore does NOTHING for an already-tracked file. That is how a
#                                  models.json full of live API keys got committed and pushed.
#   3. no binaries are committed — four stray ELFs rode along in the last tree.
#   4. no ignore pattern collides with a source dir — the root cause of (1); catch it at the pattern.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

fail=0
say()  { printf '  %s\n' "$*"; }
bad()  { printf '  ✗ %s\n' "$*"; fail=1; }
good() { printf '  ✓ %s\n' "$*"; }

echo "== 1. is any SOURCE file ignored by git? =="
# Only HAND-WRITTEN source counts. Excluded below, deliberately and narrowly:
#   data/                 runtime state (regenerated)
#   node_modules/ .next/  vendored + build output
#   config/models.json    a SECRET (the real one); models.example.json ships
#   next-env.d.ts         GENERATED by Next.js on every build; create-next-app ignores it too
# Do not widen this list to silence a failure — the failure is the point.
ignored_src=$(git ls-files --others --ignored --exclude-standard \
  | grep -E '\.(go|ts|tsx|css|json|ya?ml|md|sh|py)$' \
  | grep -vE '^(data/|frontend/node_modules/|frontend/\.next/|config/models\.json$|frontend/next-env\.d\.ts$)' || true)
if [ -n "$ignored_src" ]; then
  bad "these source files are IGNORED and would be MISSING from a clone:"
  echo "$ignored_src" | sed 's/^/      /'
else
  good "no source file is ignored"
fi

echo "== 2. is any SECRET tracked by git? =="
# .gitignore only protects UNTRACKED files — a file added before the rule stays tracked forever.
secrets=$(git ls-files | grep -iE '(^|/)(models\.json|control\.tokens|approval\.key|.*\.key|.*\.tokens|.*\.db|\.env.*)$' \
  | grep -vE '\.pub\.key$|models\.example\.json' || true)
if [ -n "$secrets" ]; then
  bad "SECRETS ARE TRACKED — rotate them, then 'git rm --cached':"
  echo "$secrets" | sed 's/^/      /'
else
  good "no secret is tracked"
fi

echo "== 3. any committed BINARIES? =="
bins=""
while IFS= read -r f; do
  [ -f "$f" ] || continue
  case "$(file -b --mime-type "$f" 2>/dev/null)" in
    application/x-executable|application/x-sharedlib|application/x-pie-executable|application/x-mach-binary)
      bins="$bins$f"$'\n' ;;
  esac
done < <(git ls-files)
if [ -n "$bins" ]; then
  bad "compiled binaries are committed:"; printf '%s' "$bins" | sed 's/^/      /'
else
  good "no committed binaries"
fi

echo "== 4. does any .gitignore pattern collide with a source directory? =="
# A bare name like `/stoa-kernel/harness` matches BOTH a binary and a directory. Git cannot tell.
collide=0
while IFS= read -r pat; do
  case "$pat" in ''|'#'*|'!'*|*/) continue ;; esac
  p="${pat#/}"
  if [ -d "$p" ] && git ls-files --error-unmatch "$p" >/dev/null 2>&1; then
    bad "pattern '$pat' matches SOURCE DIR '$p/' — it will swallow the whole tree"
    collide=1
  elif [ -d "$p" ]; then
    bad "pattern '$pat' matches the directory '$p/' (probably meant a binary). Build to bin/ instead."
    collide=1
  fi
done < <(grep -hv '^\s*$' .gitignore 2>/dev/null)
[ "$collide" -eq 0 ] && good "no ignore pattern collides with a directory"

echo
if [ "$fail" -ne 0 ]; then
  echo "HYGIENE FAILED — the repo is wrong even though the build may pass."
  exit 1
fi
echo "hygiene OK"
