#!/usr/bin/env bash
# tools/index.sh — build a searchable map of the codebase from the keyword markers in the source.
#
# The convention (inherited from the Ratchet harness this was built with):
#
#   // file-kw: mcp adapter gating proxy forward-iff-cleared quarantined tool boundary
#   // kw: gather run providers stamp untrusted fail-open per-provider
#
# `file-kw:` describes a FILE. `kw:` sits on the line above a type or func and describes THAT SYMBOL.
# They are written by whoever writes the code, because they are the thing a grep cannot infer: not what
# the code says, but what it is FOR.
#
# This produces:
#   INDEX.md          a human map — components, what each is for, where it lives
#   .index/code.json  the same thing for an agent, so a contributor can ask "where is the bit that
#                     decides an escalation?" and get a path instead of a 50-file grep.
#
# Re-run it after adding a file. CI fails if the index is stale (`tools/index.sh --check`), because an
# index nobody maintains is a map that lies — and a lying map is worse than no map.
set -euo pipefail
cd "$(dirname "$0")/.." || exit 1

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

python3 - "$CHECK" <<'PY'
import json, pathlib, re, sys, collections

check = sys.argv[1] == "1"
root = pathlib.Path(".")

# Which layer a file belongs to. This is the product's central boundary, so the index states it: the
# GATE holds no model and no keys; the ORCHESTRATOR holds them. If you are contributing, this tells you
# which side of the line your change lands on — and whether architecture_test.go is about to fail you.
def layer(p: str) -> str:
    if p.startswith("stoa-kernel/stag/"):    return "gate"
    if p.startswith("stoa-kernel/harness/"): return "orchestrator"
    if p.startswith("stoa-kernel/cmd/"):     return "binary"
    return "other"

files, missing = [], []
for p in sorted(root.glob("stoa-kernel/**/*.go")):
    sp = p.as_posix()
    if sp.endswith("_test.go"):
        continue
    src = p.read_text(errors="replace").splitlines()

    fkw, pkg, doc, symbols = [], "", "", []
    pending_kw = None
    for i, line in enumerate(src):
        s = line.strip()
        m = re.match(r"//\s*file-kw:\s*(.+)", s)
        if m:
            fkw = m.group(1).split()
            continue
        m = re.match(r"//\s*kw:\s*(.+)", s)
        if m:
            pending_kw = m.group(1).split()
            continue
        m = re.match(r"package\s+(\w+)", s)
        if m and not pkg:
            pkg = m.group(1)
            # the package doc is the comment block immediately above `package`
            j, buf = i - 1, []
            while j >= 0 and src[j].strip().startswith("//"):
                buf.append(src[j].strip().lstrip("/").strip()); j -= 1
            doc = " ".join(reversed(buf))[:220]
            continue
        m = re.match(r"(?:func|type)\s+(?:\([^)]*\)\s*)?(\w+)", s)
        if m and (pending_kw or s.startswith(("func ", "type "))):
            name = m.group(1)
            if name[:1].isupper() or pending_kw:  # exported, or explicitly annotated
                symbols.append({"name": name, "line": i + 1, "kw": pending_kw or []})
            pending_kw = None
            continue
        if s and not s.startswith("//"):
            pending_kw = None

    if not fkw:
        missing.append(sp)
    files.append({
        "path": sp, "package": pkg, "layer": layer(sp),
        "doc": doc, "keywords": fkw,
        "symbols": [s for s in symbols if s["kw"]],   # only the annotated ones are index-worthy
    })

index = {
    "note": "generated by tools/index.sh from file-kw:/kw: markers in the source — do not hand-edit",
    "layers": {
        "gate":         "stag/ — deterministic kernel, policy, MCP proxy, audit, approvals. NO model, NO keys.",
        "orchestrator": "harness/ — dispatcher, agent loop, models. HOLDS THE KEYS.",
        "binary":       "cmd/ — the shipped binaries; each is its own container.",
    },
    "files": files,
}

if check:
    old = pathlib.Path(".index/code.json")
    if not old.exists():
        print("index missing — run tools/index.sh"); sys.exit(1)
    if json.loads(old.read_text()) != index:
        print("INDEX IS STALE — a file changed but the index was not rebuilt.")
        print("  run: tools/index.sh   (and commit INDEX.md + .index/code.json)")
        sys.exit(1)
    if missing:
        print(f"{len(missing)} file(s) have no `// file-kw:` marker:")
        for m in missing: print(f"    {m}")
        print("  add one — it is the only thing a grep cannot infer: what the file is FOR.")
        sys.exit(1)
    print("index is current ✓")
    sys.exit(0)

pathlib.Path(".index").mkdir(exist_ok=True)
pathlib.Path(".index/code.json").write_text(json.dumps(index, indent=2, sort_keys=True) + "\n")

# ---- the human map ----
out = ["# Code index",
       "",
       "Generated by `tools/index.sh` from the `// file-kw:` and `// kw:` markers in the source.",
       "**Do not hand-edit.** Add a marker to the file instead and re-run.",
       "",
       "Looking for something? `tools/find.sh <words>` — e.g. `tools/find.sh escalation approval`.",
       ""]
by_layer = collections.defaultdict(list)
for f in files:
    by_layer[f["layer"]].append(f)

for lname in ("gate", "orchestrator", "binary", "other"):
    fs = by_layer.get(lname)
    if not fs: continue
    out += [f"## {lname}", "", f"> {index['layers'].get(lname,'')}", ""]
    for f in sorted(fs, key=lambda x: x["path"]):
        kw = " · ".join(f["keywords"]) or "_(no keywords — add a `// file-kw:` line)_"
        out.append(f"### `{f['path']}`")
        if f["doc"]:
            out.append(f"{f['doc']}")
        out.append("")
        out.append(f"**kw:** {kw}")
        if f["symbols"]:
            out.append("")
            for s in f["symbols"]:
                out.append(f"- `{s['name']}` (:{s['line']}) — {' · '.join(s['kw'])}")
        out.append("")

pathlib.Path("INDEX.md").write_text("\n".join(out))

nsym = sum(len(f["symbols"]) for f in files)
print(f"  indexed {len(files)} files, {nsym} annotated symbols")
print(f"  wrote INDEX.md + .index/code.json")
if missing:
    print(f"\n  {len(missing)} file(s) missing a `// file-kw:` marker:")
    for m in missing:
        print(f"    {m}")
PY
